# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.pagination import AsyncPager, SyncPager
from ...core.request_options import RequestOptions
from ...types.get_session_response import GetSessionResponse
from ...types.get_turn_response import GetTurnResponse
from ...types.list_events_response import ListEventsResponse
from ...types.list_sessions_response import ListSessionsResponse
from ...types.list_turns_response import ListTurnsResponse
from ...types.order import Order
from ...types.session import Session
from ...types.turn import Turn
from ...types.turn_event import TurnEvent
from ...types.turn_streaming_event import TurnStreamingEvent
from .raw_client import AsyncRawSessionsClient, RawSessionsClient
from .types.create_turn_request_input_item import CreateTurnRequestInputItem
from .types.create_turn_request_previous_turn_id import CreateTurnRequestPreviousTurnId
from .types.sessions_cancel_response import SessionsCancelResponse
from .types.sessions_list_turn_events_request_order import SessionsListTurnEventsRequestOrder

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SessionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSessionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSessionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSessionsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        agent_name: str,
        limit: typing.Optional[int] = 10,
        order: typing.Optional[Order] = None,
        page_token: typing.Optional[str] = None,
        start_timestamp: typing.Optional[str] = None,
        end_timestamp: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Session, ListSessionsResponse]:
        """
        List sessions for an agent (newest first by default), keyset-paginated. Pass `page_token` to fetch the next page, keeping the other query params constant.

        Parameters
        ----------
        agent_name : str

        limit : typing.Optional[int]

        order : typing.Optional[Order]

        page_token : typing.Optional[str]

        start_timestamp : typing.Optional[str]

        end_timestamp : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Session, ListSessionsResponse]
            Paginated sessions.

        Examples
        --------
        from truefoundry_gateway_sdk import Order, TrueFoundryGateway

        client = TrueFoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        response = client.agents.sessions.list(
            agent_name="agent_name",
            limit=1,
            order=Order.ASC,
            page_token="page_token",
            start_timestamp="start_timestamp",
            end_timestamp="end_timestamp",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            agent_name=agent_name,
            limit=limit,
            order=order,
            page_token=page_token,
            start_timestamp=start_timestamp,
            end_timestamp=end_timestamp,
            request_options=request_options,
        )

    def create(self, *, agent_name: str, request_options: typing.Optional[RequestOptions] = None) -> GetSessionResponse:
        """
        Create a session for an existing named agent.

        Parameters
        ----------
        agent_name : str
            Name of an existing agent in the tenant.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSessionResponse
            Session created.

        Examples
        --------
        from truefoundry_gateway_sdk import TrueFoundryGateway

        client = TrueFoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.agents.sessions.create(
            agent_name="agent_name",
        )
        """
        _response = self._raw_client.create(agent_name=agent_name, request_options=request_options)
        return _response.data

    def get(self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetSessionResponse:
        """
        Get a session by id. Visible to the session owner or a manager of the session agent.

        Parameters
        ----------
        session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSessionResponse
            Session data.

        Examples
        --------
        from truefoundry_gateway_sdk import TrueFoundryGateway

        client = TrueFoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.agents.sessions.get(
            session_id="sessionId",
        )
        """
        _response = self._raw_client.get(session_id, request_options=request_options)
        return _response.data

    def cancel(
        self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SessionsCancelResponse:
        """
        Cancel the running last turn for a session.

        Parameters
        ----------
        session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SessionsCancelResponse
            Turn cancelled.

        Examples
        --------
        from truefoundry_gateway_sdk import TrueFoundryGateway

        client = TrueFoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.agents.sessions.cancel(
            session_id="01arz3ndektsv4rrffq69g5fav.g",
        )
        """
        _response = self._raw_client.cancel(session_id, request_options=request_options)
        return _response.data

    def list_turns(
        self,
        session_id: str,
        *,
        page_token: typing.Optional[str] = None,
        limit: typing.Optional[int] = 10,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Turn, ListTurnsResponse]:
        """
        List turns for a session (newest first). Pagination walks the ancestor chain from the session last turn, or from the turn in page_token when continuing.

        Parameters
        ----------
        session_id : str

        page_token : typing.Optional[str]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Turn, ListTurnsResponse]
            Paginated turns.

        Examples
        --------
        from truefoundry_gateway_sdk import TrueFoundryGateway

        client = TrueFoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        response = client.agents.sessions.list_turns(
            session_id="01arz3ndektsv4rrffq69g5fav.g",
            page_token="page_token",
            limit=1,
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_turns(
            session_id, page_token=page_token, limit=limit, request_options=request_options
        )

    def create_turn(
        self,
        session_id: str,
        *,
        input: typing.Optional[typing.Sequence[CreateTurnRequestInputItem]] = OMIT,
        previous_turn_id: typing.Optional[CreateTurnRequestPreviousTurnId] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[TurnStreamingEvent]:
        """
        Start or continue a turn within a session. Responds with a Server-Sent Events stream.
        Use `previous_turn_id` to chain to the session's last turn (defaults to `auto`).

        Parameters
        ----------
        session_id : str

        input : typing.Optional[typing.Sequence[CreateTurnRequestInputItem]]

        previous_turn_id : typing.Optional[CreateTurnRequestPreviousTurnId]
            Defaults to 'auto' (chain to session last turn). Use 'null' for the session's first turn.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[TurnStreamingEvent]
            Server-Sent Events stream of turn events.

        Examples
        --------
        from truefoundry_gateway_sdk import TrueFoundryGateway

        client = TrueFoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        response = client.agents.sessions.create_turn(
            session_id="01arz3ndektsv4rrffq69g5fav.g",
        )
        for chunk in response:
            yield chunk
        """
        with self._raw_client.create_turn(
            session_id, input=input, previous_turn_id=previous_turn_id, request_options=request_options
        ) as r:
            yield from r.data

    def get_turn(
        self, session_id: str, turn_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetTurnResponse:
        """
        Get a single turn by ID from Redis.

        Parameters
        ----------
        session_id : str

        turn_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetTurnResponse
            Turn data.

        Examples
        --------
        from truefoundry_gateway_sdk import TrueFoundryGateway

        client = TrueFoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.agents.sessions.get_turn(
            session_id="01arz3ndektsv4rrffq69g5fav.g",
            turn_id="01arz3ndektsv4rrffq69g5fav.g.ab12cd",
        )
        """
        _response = self._raw_client.get_turn(session_id, turn_id, request_options=request_options)
        return _response.data

    def subscribe_to_turn(
        self,
        session_id: str,
        turn_id: str,
        *,
        after_sequence_number: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[TurnStreamingEvent]:
        """
        Subscribe to the live SSE stream for a turn. Pass after_sequence_number to resume after disconnect or server timeout, or send Last-Event-Id when after_sequence_number is omitted.

        Parameters
        ----------
        session_id : str

        turn_id : str

        after_sequence_number : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[TurnStreamingEvent]
            Server-Sent Events stream of turn events (deltas and lifecycle).

        Examples
        --------
        from truefoundry_gateway_sdk import TrueFoundryGateway

        client = TrueFoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        response = client.agents.sessions.subscribe_to_turn(
            session_id="01arz3ndektsv4rrffq69g5fav.g",
            turn_id="01arz3ndektsv4rrffq69g5fav.g.ab12cd",
        )
        for chunk in response:
            yield chunk
        """
        with self._raw_client.subscribe_to_turn(
            session_id, turn_id, after_sequence_number=after_sequence_number, request_options=request_options
        ) as r:
            yield from r.data

    def list_turn_events(
        self,
        session_id: str,
        turn_id: str,
        *,
        page_token: typing.Optional[str] = None,
        limit: typing.Optional[int] = 25,
        order: typing.Optional[SessionsListTurnEventsRequestOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[TurnEvent, ListEventsResponse]:
        """
        Paginated list of turn events from the Redis events stream.

        Parameters
        ----------
        session_id : str

        turn_id : str

        page_token : typing.Optional[str]

        limit : typing.Optional[int]

        order : typing.Optional[SessionsListTurnEventsRequestOrder]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[TurnEvent, ListEventsResponse]
            Paginated events.

        Examples
        --------
        from truefoundry_gateway_sdk import TrueFoundryGateway
        from truefoundry_gateway_sdk.agents.sessions import (
            SessionsListTurnEventsRequestOrder,
        )

        client = TrueFoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        response = client.agents.sessions.list_turn_events(
            session_id="01arz3ndektsv4rrffq69g5fav.g",
            turn_id="01arz3ndektsv4rrffq69g5fav.g.ab12cd",
            page_token="page_token",
            limit=1,
            order=SessionsListTurnEventsRequestOrder.ASC,
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_turn_events(
            session_id, turn_id, page_token=page_token, limit=limit, order=order, request_options=request_options
        )


class AsyncSessionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSessionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSessionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSessionsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        agent_name: str,
        limit: typing.Optional[int] = 10,
        order: typing.Optional[Order] = None,
        page_token: typing.Optional[str] = None,
        start_timestamp: typing.Optional[str] = None,
        end_timestamp: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Session, ListSessionsResponse]:
        """
        List sessions for an agent (newest first by default), keyset-paginated. Pass `page_token` to fetch the next page, keeping the other query params constant.

        Parameters
        ----------
        agent_name : str

        limit : typing.Optional[int]

        order : typing.Optional[Order]

        page_token : typing.Optional[str]

        start_timestamp : typing.Optional[str]

        end_timestamp : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Session, ListSessionsResponse]
            Paginated sessions.

        Examples
        --------
        import asyncio

        from truefoundry_gateway_sdk import AsyncTrueFoundryGateway, Order

        client = AsyncTrueFoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            response = await client.agents.sessions.list(
                agent_name="agent_name",
                limit=1,
                order=Order.ASC,
                page_token="page_token",
                start_timestamp="start_timestamp",
                end_timestamp="end_timestamp",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            agent_name=agent_name,
            limit=limit,
            order=order,
            page_token=page_token,
            start_timestamp=start_timestamp,
            end_timestamp=end_timestamp,
            request_options=request_options,
        )

    async def create(
        self, *, agent_name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> GetSessionResponse:
        """
        Create a session for an existing named agent.

        Parameters
        ----------
        agent_name : str
            Name of an existing agent in the tenant.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSessionResponse
            Session created.

        Examples
        --------
        import asyncio

        from truefoundry_gateway_sdk import AsyncTrueFoundryGateway

        client = AsyncTrueFoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.agents.sessions.create(
                agent_name="agent_name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(agent_name=agent_name, request_options=request_options)
        return _response.data

    async def get(
        self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetSessionResponse:
        """
        Get a session by id. Visible to the session owner or a manager of the session agent.

        Parameters
        ----------
        session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSessionResponse
            Session data.

        Examples
        --------
        import asyncio

        from truefoundry_gateway_sdk import AsyncTrueFoundryGateway

        client = AsyncTrueFoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.agents.sessions.get(
                session_id="sessionId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(session_id, request_options=request_options)
        return _response.data

    async def cancel(
        self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SessionsCancelResponse:
        """
        Cancel the running last turn for a session.

        Parameters
        ----------
        session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SessionsCancelResponse
            Turn cancelled.

        Examples
        --------
        import asyncio

        from truefoundry_gateway_sdk import AsyncTrueFoundryGateway

        client = AsyncTrueFoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.agents.sessions.cancel(
                session_id="01arz3ndektsv4rrffq69g5fav.g",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel(session_id, request_options=request_options)
        return _response.data

    async def list_turns(
        self,
        session_id: str,
        *,
        page_token: typing.Optional[str] = None,
        limit: typing.Optional[int] = 10,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Turn, ListTurnsResponse]:
        """
        List turns for a session (newest first). Pagination walks the ancestor chain from the session last turn, or from the turn in page_token when continuing.

        Parameters
        ----------
        session_id : str

        page_token : typing.Optional[str]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Turn, ListTurnsResponse]
            Paginated turns.

        Examples
        --------
        import asyncio

        from truefoundry_gateway_sdk import AsyncTrueFoundryGateway

        client = AsyncTrueFoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            response = await client.agents.sessions.list_turns(
                session_id="01arz3ndektsv4rrffq69g5fav.g",
                page_token="page_token",
                limit=1,
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_turns(
            session_id, page_token=page_token, limit=limit, request_options=request_options
        )

    async def create_turn(
        self,
        session_id: str,
        *,
        input: typing.Optional[typing.Sequence[CreateTurnRequestInputItem]] = OMIT,
        previous_turn_id: typing.Optional[CreateTurnRequestPreviousTurnId] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[TurnStreamingEvent]:
        """
        Start or continue a turn within a session. Responds with a Server-Sent Events stream.
        Use `previous_turn_id` to chain to the session's last turn (defaults to `auto`).

        Parameters
        ----------
        session_id : str

        input : typing.Optional[typing.Sequence[CreateTurnRequestInputItem]]

        previous_turn_id : typing.Optional[CreateTurnRequestPreviousTurnId]
            Defaults to 'auto' (chain to session last turn). Use 'null' for the session's first turn.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[TurnStreamingEvent]
            Server-Sent Events stream of turn events.

        Examples
        --------
        import asyncio

        from truefoundry_gateway_sdk import AsyncTrueFoundryGateway

        client = AsyncTrueFoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            response = await client.agents.sessions.create_turn(
                session_id="01arz3ndektsv4rrffq69g5fav.g",
            )
            async for chunk in response:
                yield chunk


        asyncio.run(main())
        """
        async with self._raw_client.create_turn(
            session_id, input=input, previous_turn_id=previous_turn_id, request_options=request_options
        ) as r:
            async for _chunk in r.data:
                yield _chunk

    async def get_turn(
        self, session_id: str, turn_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetTurnResponse:
        """
        Get a single turn by ID from Redis.

        Parameters
        ----------
        session_id : str

        turn_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetTurnResponse
            Turn data.

        Examples
        --------
        import asyncio

        from truefoundry_gateway_sdk import AsyncTrueFoundryGateway

        client = AsyncTrueFoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.agents.sessions.get_turn(
                session_id="01arz3ndektsv4rrffq69g5fav.g",
                turn_id="01arz3ndektsv4rrffq69g5fav.g.ab12cd",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_turn(session_id, turn_id, request_options=request_options)
        return _response.data

    async def subscribe_to_turn(
        self,
        session_id: str,
        turn_id: str,
        *,
        after_sequence_number: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[TurnStreamingEvent]:
        """
        Subscribe to the live SSE stream for a turn. Pass after_sequence_number to resume after disconnect or server timeout, or send Last-Event-Id when after_sequence_number is omitted.

        Parameters
        ----------
        session_id : str

        turn_id : str

        after_sequence_number : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[TurnStreamingEvent]
            Server-Sent Events stream of turn events (deltas and lifecycle).

        Examples
        --------
        import asyncio

        from truefoundry_gateway_sdk import AsyncTrueFoundryGateway

        client = AsyncTrueFoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            response = await client.agents.sessions.subscribe_to_turn(
                session_id="01arz3ndektsv4rrffq69g5fav.g",
                turn_id="01arz3ndektsv4rrffq69g5fav.g.ab12cd",
            )
            async for chunk in response:
                yield chunk


        asyncio.run(main())
        """
        async with self._raw_client.subscribe_to_turn(
            session_id, turn_id, after_sequence_number=after_sequence_number, request_options=request_options
        ) as r:
            async for _chunk in r.data:
                yield _chunk

    async def list_turn_events(
        self,
        session_id: str,
        turn_id: str,
        *,
        page_token: typing.Optional[str] = None,
        limit: typing.Optional[int] = 25,
        order: typing.Optional[SessionsListTurnEventsRequestOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[TurnEvent, ListEventsResponse]:
        """
        Paginated list of turn events from the Redis events stream.

        Parameters
        ----------
        session_id : str

        turn_id : str

        page_token : typing.Optional[str]

        limit : typing.Optional[int]

        order : typing.Optional[SessionsListTurnEventsRequestOrder]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[TurnEvent, ListEventsResponse]
            Paginated events.

        Examples
        --------
        import asyncio

        from truefoundry_gateway_sdk import AsyncTrueFoundryGateway
        from truefoundry_gateway_sdk.agents.sessions import (
            SessionsListTurnEventsRequestOrder,
        )

        client = AsyncTrueFoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            response = await client.agents.sessions.list_turn_events(
                session_id="01arz3ndektsv4rrffq69g5fav.g",
                turn_id="01arz3ndektsv4rrffq69g5fav.g.ab12cd",
                page_token="page_token",
                limit=1,
                order=SessionsListTurnEventsRequestOrder.ASC,
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_turn_events(
            session_id, turn_id, page_token=page_token, limit=limit, order=order, request_options=request_options
        )
