# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_draft_session_request_agent_spec import CreateDraftSessionRequestAgentSpec
    from .create_draft_session_request_agent_spec_messages_item import CreateDraftSessionRequestAgentSpecMessagesItem
    from .draft_sessions_create_response import DraftSessionsCreateResponse
    from .draft_sessions_get_response import DraftSessionsGetResponse
    from .draft_sessions_list_response import DraftSessionsListResponse
    from .draft_sessions_update_response import DraftSessionsUpdateResponse
    from .update_draft_session_request_agent_spec import UpdateDraftSessionRequestAgentSpec
    from .update_draft_session_request_agent_spec_messages_item import UpdateDraftSessionRequestAgentSpecMessagesItem
_dynamic_imports: typing.Dict[str, str] = {
    "CreateDraftSessionRequestAgentSpec": ".create_draft_session_request_agent_spec",
    "CreateDraftSessionRequestAgentSpecMessagesItem": ".create_draft_session_request_agent_spec_messages_item",
    "DraftSessionsCreateResponse": ".draft_sessions_create_response",
    "DraftSessionsGetResponse": ".draft_sessions_get_response",
    "DraftSessionsListResponse": ".draft_sessions_list_response",
    "DraftSessionsUpdateResponse": ".draft_sessions_update_response",
    "UpdateDraftSessionRequestAgentSpec": ".update_draft_session_request_agent_spec",
    "UpdateDraftSessionRequestAgentSpecMessagesItem": ".update_draft_session_request_agent_spec_messages_item",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateDraftSessionRequestAgentSpec",
    "CreateDraftSessionRequestAgentSpecMessagesItem",
    "DraftSessionsCreateResponse",
    "DraftSessionsGetResponse",
    "DraftSessionsListResponse",
    "DraftSessionsUpdateResponse",
    "UpdateDraftSessionRequestAgentSpec",
    "UpdateDraftSessionRequestAgentSpecMessagesItem",
]
