# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ....core.api_error import ApiError
from ....core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ....core.pagination import AsyncPager, SyncPager
from ....core.parse_error import ParsingError
from ....core.pydantic_utilities import parse_obj_as
from ....core.request_options import RequestOptions
from ....errors.bad_request_error import BadRequestError
from ....errors.not_found_error import NotFoundError
from ....errors.unauthorized_error import UnauthorizedError
from ....errors.unprocessable_entity_error import UnprocessableEntityError
from ....types.list_owned_sessions_order import ListOwnedSessionsOrder
from ....types.list_owned_sessions_response import ListOwnedSessionsResponse
from ....types.list_owned_sessions_response_data_item import ListOwnedSessionsResponseDataItem
from ....types.request_error_response import RequestErrorResponse
from pydantic import ValidationError


class RawPrivateClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_owned_sessions(
        self,
        *,
        agent_name: typing.Optional[str] = None,
        limit: typing.Optional[int] = 10,
        order: typing.Optional[ListOwnedSessionsOrder] = None,
        page_token: typing.Optional[str] = None,
        start_timestamp: typing.Optional[str] = None,
        end_timestamp: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[ListOwnedSessionsResponseDataItem, ListOwnedSessionsResponse]:
        """
        List all sessions owned by the caller, spanning both saved sessions and drafts (newest first by default), keyset-paginated. Optionally filter by `agent_name`. Pass `page_token` to fetch the next page, keeping the other query params constant.

        Parameters
        ----------
        agent_name : typing.Optional[str]
            Filter to sessions linked to this saved agent. Omit to list all of the caller-owned sessions.

        limit : typing.Optional[int]
            Page size. Defaults to 10, max 100.

        order : typing.Optional[ListOwnedSessionsOrder]
            Sort sessions by creation time. Defaults to "desc".

        page_token : typing.Optional[str]
            Opaque token from a previous response `next_page_token`.

        start_timestamp : typing.Optional[str]
            Inclusive lower bound on `created_at` (ISO-8601). Defaults upstream to 30 min before `end_timestamp`.

        end_timestamp : typing.Optional[str]
            Inclusive upper bound on `created_at` (ISO-8601). Defaults upstream to now.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[ListOwnedSessionsResponseDataItem, ListOwnedSessionsResponse]
            Paginated caller-owned sessions.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/x/agents/owned-sessions",
            method="GET",
            params={
                "agent_name": agent_name,
                "limit": limit,
                "order": order,
                "page_token": page_token,
                "start_timestamp": start_timestamp,
                "end_timestamp": end_timestamp,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListOwnedSessionsResponse,
                    parse_obj_as(
                        type_=ListOwnedSessionsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.data
                _has_next = False
                _get_next = None
                if _parsed_response.pagination is not None:
                    _parsed_next = _parsed_response.pagination.next_page_token
                    _has_next = _parsed_next is not None and _parsed_next != ""
                    _get_next = lambda: self.list_owned_sessions(
                        agent_name=agent_name,
                        limit=limit,
                        order=order,
                        page_token=_parsed_next,
                        start_timestamp=start_timestamp,
                        end_timestamp=end_timestamp,
                        request_options=request_options,
                    )
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        RequestErrorResponse,
                        parse_obj_as(
                            type_=RequestErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        RequestErrorResponse,
                        parse_obj_as(
                            type_=RequestErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        RequestErrorResponse,
                        parse_obj_as(
                            type_=RequestErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        RequestErrorResponse,
                        parse_obj_as(
                            type_=RequestErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawPrivateClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_owned_sessions(
        self,
        *,
        agent_name: typing.Optional[str] = None,
        limit: typing.Optional[int] = 10,
        order: typing.Optional[ListOwnedSessionsOrder] = None,
        page_token: typing.Optional[str] = None,
        start_timestamp: typing.Optional[str] = None,
        end_timestamp: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[ListOwnedSessionsResponseDataItem, ListOwnedSessionsResponse]:
        """
        List all sessions owned by the caller, spanning both saved sessions and drafts (newest first by default), keyset-paginated. Optionally filter by `agent_name`. Pass `page_token` to fetch the next page, keeping the other query params constant.

        Parameters
        ----------
        agent_name : typing.Optional[str]
            Filter to sessions linked to this saved agent. Omit to list all of the caller-owned sessions.

        limit : typing.Optional[int]
            Page size. Defaults to 10, max 100.

        order : typing.Optional[ListOwnedSessionsOrder]
            Sort sessions by creation time. Defaults to "desc".

        page_token : typing.Optional[str]
            Opaque token from a previous response `next_page_token`.

        start_timestamp : typing.Optional[str]
            Inclusive lower bound on `created_at` (ISO-8601). Defaults upstream to 30 min before `end_timestamp`.

        end_timestamp : typing.Optional[str]
            Inclusive upper bound on `created_at` (ISO-8601). Defaults upstream to now.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[ListOwnedSessionsResponseDataItem, ListOwnedSessionsResponse]
            Paginated caller-owned sessions.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/x/agents/owned-sessions",
            method="GET",
            params={
                "agent_name": agent_name,
                "limit": limit,
                "order": order,
                "page_token": page_token,
                "start_timestamp": start_timestamp,
                "end_timestamp": end_timestamp,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListOwnedSessionsResponse,
                    parse_obj_as(
                        type_=ListOwnedSessionsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.data
                _has_next = False
                _get_next = None
                if _parsed_response.pagination is not None:
                    _parsed_next = _parsed_response.pagination.next_page_token
                    _has_next = _parsed_next is not None and _parsed_next != ""

                    async def _get_next():
                        return await self.list_owned_sessions(
                            agent_name=agent_name,
                            limit=limit,
                            order=order,
                            page_token=_parsed_next,
                            start_timestamp=start_timestamp,
                            end_timestamp=end_timestamp,
                            request_options=request_options,
                        )

                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        RequestErrorResponse,
                        parse_obj_as(
                            type_=RequestErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        RequestErrorResponse,
                        parse_obj_as(
                            type_=RequestErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        RequestErrorResponse,
                        parse_obj_as(
                            type_=RequestErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        RequestErrorResponse,
                        parse_obj_as(
                            type_=RequestErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
