# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.api_error import ApiError
from ..types.agent_error_response import AgentErrorResponse


class InternalServerError(ApiError):
    def __init__(self, body: AgentErrorResponse, headers: typing.Optional[typing.Dict[str, str]] = None):
        super().__init__(status_code=500, headers=headers, body=body)
