# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_turn_request_input_item import CreateTurnRequestInputItem
    from .create_turn_request_previous_turn_id import CreateTurnRequestPreviousTurnId
    from .sessions_cancel_response import SessionsCancelResponse
    from .sessions_create_response import SessionsCreateResponse
    from .sessions_get_response import SessionsGetResponse
    from .sessions_get_turn_response import SessionsGetTurnResponse
    from .sessions_list_request_order import SessionsListRequestOrder
    from .sessions_list_response import SessionsListResponse
    from .sessions_list_turn_events_request_order import SessionsListTurnEventsRequestOrder
    from .sessions_list_turn_events_response import SessionsListTurnEventsResponse
    from .sessions_list_turns_response import SessionsListTurnsResponse
_dynamic_imports: typing.Dict[str, str] = {
    "CreateTurnRequestInputItem": ".create_turn_request_input_item",
    "CreateTurnRequestPreviousTurnId": ".create_turn_request_previous_turn_id",
    "SessionsCancelResponse": ".sessions_cancel_response",
    "SessionsCreateResponse": ".sessions_create_response",
    "SessionsGetResponse": ".sessions_get_response",
    "SessionsGetTurnResponse": ".sessions_get_turn_response",
    "SessionsListRequestOrder": ".sessions_list_request_order",
    "SessionsListResponse": ".sessions_list_response",
    "SessionsListTurnEventsRequestOrder": ".sessions_list_turn_events_request_order",
    "SessionsListTurnEventsResponse": ".sessions_list_turn_events_response",
    "SessionsListTurnsResponse": ".sessions_list_turns_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateTurnRequestInputItem",
    "CreateTurnRequestPreviousTurnId",
    "SessionsCancelResponse",
    "SessionsCreateResponse",
    "SessionsGetResponse",
    "SessionsGetTurnResponse",
    "SessionsListRequestOrder",
    "SessionsListResponse",
    "SessionsListTurnEventsRequestOrder",
    "SessionsListTurnEventsResponse",
    "SessionsListTurnsResponse",
]
