# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.agent_response_streaming_output_event import AgentResponseStreamingOutputEvent
from ...types.agent_responses_body import AgentResponsesBody
from .raw_client import AsyncRawResponsesClient, RawResponsesClient
from .types.responses_cancel_response import ResponsesCancelResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ResponsesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawResponsesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawResponsesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawResponsesClient
        """
        return self._raw_client

    def create(
        self, *, request: AgentResponsesBody, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[AgentResponseStreamingOutputEvent]:
        """
        Execute an agent in stateful mode (responses are stored server-side by default). Use Named (`agent_name`) or Inline (`model`) input. Continue a conversation with `previous_response_id`. Responds with a Server-Sent Events stream of `AgentResponseStreamingOutputEvent` objects.

        Parameters
        ----------
        request : AgentResponsesBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[AgentResponseStreamingOutputEvent]
            Server-Sent Events stream of agent response events.

        Examples
        --------
        from truefoundry_gateway_sdk import (
            AgentResponsesInlineAgent,
            TruefoundryGateway,
        )

        client = TruefoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        response = client.agents.responses.create(
            request=AgentResponsesInlineAgent(
                model="model",
            ),
        )
        for chunk in response:
            yield chunk
        """
        with self._raw_client.create(request=request, request_options=request_options) as r:
            yield from r.data

    def cancel(
        self, *, response_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ResponsesCancelResponse:
        """
        Cancel a running agent response. Requires the `response_id` returned from a prior stateful `/responses` call.

        Parameters
        ----------
        response_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResponsesCancelResponse
            Response run cancelled successfully

        Examples
        --------
        from truefoundry_gateway_sdk import TruefoundryGateway

        client = TruefoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.agents.responses.cancel(
            response_id="response_id",
        )
        """
        _response = self._raw_client.cancel(response_id=response_id, request_options=request_options)
        return _response.data


class AsyncResponsesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawResponsesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawResponsesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawResponsesClient
        """
        return self._raw_client

    async def create(
        self, *, request: AgentResponsesBody, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[AgentResponseStreamingOutputEvent]:
        """
        Execute an agent in stateful mode (responses are stored server-side by default). Use Named (`agent_name`) or Inline (`model`) input. Continue a conversation with `previous_response_id`. Responds with a Server-Sent Events stream of `AgentResponseStreamingOutputEvent` objects.

        Parameters
        ----------
        request : AgentResponsesBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[AgentResponseStreamingOutputEvent]
            Server-Sent Events stream of agent response events.

        Examples
        --------
        import asyncio

        from truefoundry_gateway_sdk import (
            AgentResponsesInlineAgent,
            AsyncTruefoundryGateway,
        )

        client = AsyncTruefoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            response = await client.agents.responses.create(
                request=AgentResponsesInlineAgent(
                    model="model",
                ),
            )
            async for chunk in response:
                yield chunk


        asyncio.run(main())
        """
        async with self._raw_client.create(request=request, request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk

    async def cancel(
        self, *, response_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ResponsesCancelResponse:
        """
        Cancel a running agent response. Requires the `response_id` returned from a prior stateful `/responses` call.

        Parameters
        ----------
        response_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResponsesCancelResponse
            Response run cancelled successfully

        Examples
        --------
        import asyncio

        from truefoundry_gateway_sdk import AsyncTruefoundryGateway

        client = AsyncTruefoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.agents.responses.cancel(
                response_id="response_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel(response_id=response_id, request_options=request_options)
        return _response.data
