# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.agent_approval_decision_message import AgentApprovalDecisionMessage
from ...types.agent_response_streaming_output_event import AgentResponseStreamingOutputEvent
from ...types.agent_run_input import AgentRunInput
from ...types.internal_agent_response_streaming_output_event import InternalAgentResponseStreamingOutputEvent
from .raw_client import AsyncRawResponsesClient, RawResponsesClient
from .types.responses_cancel_response import ResponsesCancelResponse
from .types.responses_get_response import ResponsesGetResponse
from .types.responses_send_message_response import ResponsesSendMessageResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ResponsesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawResponsesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawResponsesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawResponsesClient
        """
        return self._raw_client

    def create(
        self, *, request: AgentRunInput, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[AgentResponseStreamingOutputEvent]:
        """
        Execute an agent in stateful mode (responses are stored server-side by default). Use Named (`agent_name`) or Inline (`model`) input. Continue a conversation with `previous_response_id`. Responds with a Server-Sent Events stream of `AgentResponseStreamingOutputEvent` objects.

        Parameters
        ----------
        request : AgentRunInput

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[AgentResponseStreamingOutputEvent]
            Server-Sent Events stream of agent response events.

        Examples
        --------
        from truefoundry_gateway_sdk import NamedAgentRunInput, TruefoundryGateway

        client = TruefoundryGateway(
            token="YOUR_TOKEN",
        )
        response = client.agent.responses.create(
            request=NamedAgentRunInput(
                agent_name="agent_name",
            ),
        )
        for chunk in response:
            yield chunk
        """
        with self._raw_client.create(request=request, request_options=request_options) as r:
            yield from r.data

    def cancel(
        self, *, response_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ResponsesCancelResponse:
        """
        Cancel a running agent response. Requires the `response_id` returned from a prior stateful `/responses` call.

        Parameters
        ----------
        response_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResponsesCancelResponse
            Response run cancelled successfully

        Examples
        --------
        from truefoundry_gateway_sdk import TruefoundryGateway

        client = TruefoundryGateway(
            token="YOUR_TOKEN",
        )
        client.agent.responses.cancel(
            response_id="response_id",
        )
        """
        _response = self._raw_client.cancel(response_id=response_id, request_options=request_options)
        return _response.data

    def get(self, response_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ResponsesGetResponse:
        """
        Returns the current state of an agent response.

        Parameters
        ----------
        response_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResponsesGetResponse
            Agent response state.

        Examples
        --------
        from truefoundry_gateway_sdk import TruefoundryGateway

        client = TruefoundryGateway(
            token="YOUR_TOKEN",
        )
        client.agent.responses.get(
            response_id="responseId",
        )
        """
        _response = self._raw_client.get(response_id, request_options=request_options)
        return _response.data

    def send_message(
        self,
        *,
        response_id: str,
        input: typing.Sequence[AgentApprovalDecisionMessage],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ResponsesSendMessageResponse:
        """
        Send approval decisions (allow/deny) to a running agent response awaiting user input.

        Parameters
        ----------
        response_id : str

        input : typing.Sequence[AgentApprovalDecisionMessage]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResponsesSendMessageResponse
            Approval decisions appended successfully

        Examples
        --------
        from truefoundry_gateway_sdk import (
            AgentApprovalDecisionMessage,
            AgentApprovalDecisionZero,
            TruefoundryGateway,
        )

        client = TruefoundryGateway(
            token="YOUR_TOKEN",
        )
        client.agent.responses.send_message(
            response_id="response_id",
            input=[
                AgentApprovalDecisionMessage(
                    execution_id="execution_id",
                    tool_call_id="tool_call_id",
                    approval=AgentApprovalDecisionZero(),
                )
            ],
        )
        """
        _response = self._raw_client.send_message(response_id=response_id, input=input, request_options=request_options)
        return _response.data

    def subscribe(
        self,
        *,
        response_id: str,
        sequence_id: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[InternalAgentResponseStreamingOutputEvent]:
        """
        Subscribe to a running agent response.

        Parameters
        ----------
        response_id : str

        sequence_id : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[InternalAgentResponseStreamingOutputEvent]
            Streaming response chunks for the subscribed agent execution.

        Examples
        --------
        from truefoundry_gateway_sdk import TruefoundryGateway

        client = TruefoundryGateway(
            token="YOUR_TOKEN",
        )
        response = client.agent.responses.subscribe(
            response_id="response_id",
        )
        for chunk in response:
            yield chunk
        """
        with self._raw_client.subscribe(
            response_id=response_id, sequence_id=sequence_id, request_options=request_options
        ) as r:
            yield from r.data


class AsyncResponsesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawResponsesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawResponsesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawResponsesClient
        """
        return self._raw_client

    async def create(
        self, *, request: AgentRunInput, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[AgentResponseStreamingOutputEvent]:
        """
        Execute an agent in stateful mode (responses are stored server-side by default). Use Named (`agent_name`) or Inline (`model`) input. Continue a conversation with `previous_response_id`. Responds with a Server-Sent Events stream of `AgentResponseStreamingOutputEvent` objects.

        Parameters
        ----------
        request : AgentRunInput

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[AgentResponseStreamingOutputEvent]
            Server-Sent Events stream of agent response events.

        Examples
        --------
        import asyncio

        from truefoundry_gateway_sdk import AsyncTruefoundryGateway, NamedAgentRunInput

        client = AsyncTruefoundryGateway(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.agent.responses.create(
                request=NamedAgentRunInput(
                    agent_name="agent_name",
                ),
            )
            async for chunk in response:
                yield chunk


        asyncio.run(main())
        """
        async with self._raw_client.create(request=request, request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk

    async def cancel(
        self, *, response_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ResponsesCancelResponse:
        """
        Cancel a running agent response. Requires the `response_id` returned from a prior stateful `/responses` call.

        Parameters
        ----------
        response_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResponsesCancelResponse
            Response run cancelled successfully

        Examples
        --------
        import asyncio

        from truefoundry_gateway_sdk import AsyncTruefoundryGateway

        client = AsyncTruefoundryGateway(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agent.responses.cancel(
                response_id="response_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel(response_id=response_id, request_options=request_options)
        return _response.data

    async def get(
        self, response_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ResponsesGetResponse:
        """
        Returns the current state of an agent response.

        Parameters
        ----------
        response_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResponsesGetResponse
            Agent response state.

        Examples
        --------
        import asyncio

        from truefoundry_gateway_sdk import AsyncTruefoundryGateway

        client = AsyncTruefoundryGateway(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agent.responses.get(
                response_id="responseId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(response_id, request_options=request_options)
        return _response.data

    async def send_message(
        self,
        *,
        response_id: str,
        input: typing.Sequence[AgentApprovalDecisionMessage],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ResponsesSendMessageResponse:
        """
        Send approval decisions (allow/deny) to a running agent response awaiting user input.

        Parameters
        ----------
        response_id : str

        input : typing.Sequence[AgentApprovalDecisionMessage]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResponsesSendMessageResponse
            Approval decisions appended successfully

        Examples
        --------
        import asyncio

        from truefoundry_gateway_sdk import (
            AgentApprovalDecisionMessage,
            AgentApprovalDecisionZero,
            AsyncTruefoundryGateway,
        )

        client = AsyncTruefoundryGateway(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agent.responses.send_message(
                response_id="response_id",
                input=[
                    AgentApprovalDecisionMessage(
                        execution_id="execution_id",
                        tool_call_id="tool_call_id",
                        approval=AgentApprovalDecisionZero(),
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.send_message(
            response_id=response_id, input=input, request_options=request_options
        )
        return _response.data

    async def subscribe(
        self,
        *,
        response_id: str,
        sequence_id: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[InternalAgentResponseStreamingOutputEvent]:
        """
        Subscribe to a running agent response.

        Parameters
        ----------
        response_id : str

        sequence_id : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[InternalAgentResponseStreamingOutputEvent]
            Streaming response chunks for the subscribed agent execution.

        Examples
        --------
        import asyncio

        from truefoundry_gateway_sdk import AsyncTruefoundryGateway

        client = AsyncTruefoundryGateway(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.agent.responses.subscribe(
                response_id="response_id",
            )
            async for chunk in response:
                yield chunk


        asyncio.run(main())
        """
        async with self._raw_client.subscribe(
            response_id=response_id, sequence_id=sequence_id, request_options=request_options
        ) as r:
            async for _chunk in r.data:
                yield _chunk
