# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawAgentsClient, RawAgentsClient

if typing.TYPE_CHECKING:
    from .draft_sessions.client import AsyncDraftSessionsClient, DraftSessionsClient
    from .sessions.client import AsyncSessionsClient, SessionsClient


class AgentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._draft_sessions: typing.Optional[DraftSessionsClient] = None
        self._sessions: typing.Optional[SessionsClient] = None

    @property
    def with_raw_response(self) -> RawAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentsClient
        """
        return self._raw_client

    def download_sandbox_file(
        self, sandbox_id: str, *, path: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[bytes]:
        """
        Download a file produced by an agent inside a sandbox.

        Parameters
        ----------
        sandbox_id : str
            The sandbox containing the file.

        path : str
            Absolute path of the file inside the sandbox.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            File download.

        Examples
        --------
        from truefoundry_gateway_sdk import TrueFoundryGateway

        client = TrueFoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.private.agents.download_sandbox_file(
            sandbox_id="sandboxId",
            path="x",
        )
        """
        with self._raw_client.download_sandbox_file(sandbox_id, path=path, request_options=request_options) as r:
            yield from r.data

    @property
    def draft_sessions(self):
        if self._draft_sessions is None:
            from .draft_sessions.client import DraftSessionsClient  # noqa: E402

            self._draft_sessions = DraftSessionsClient(client_wrapper=self._client_wrapper)
        return self._draft_sessions

    @property
    def sessions(self):
        if self._sessions is None:
            from .sessions.client import SessionsClient  # noqa: E402

            self._sessions = SessionsClient(client_wrapper=self._client_wrapper)
        return self._sessions


class AsyncAgentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._draft_sessions: typing.Optional[AsyncDraftSessionsClient] = None
        self._sessions: typing.Optional[AsyncSessionsClient] = None

    @property
    def with_raw_response(self) -> AsyncRawAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentsClient
        """
        return self._raw_client

    async def download_sandbox_file(
        self, sandbox_id: str, *, path: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[bytes]:
        """
        Download a file produced by an agent inside a sandbox.

        Parameters
        ----------
        sandbox_id : str
            The sandbox containing the file.

        path : str
            Absolute path of the file inside the sandbox.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            File download.

        Examples
        --------
        import asyncio

        from truefoundry_gateway_sdk import AsyncTrueFoundryGateway

        client = AsyncTrueFoundryGateway(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.private.agents.download_sandbox_file(
                sandbox_id="sandboxId",
                path="x",
            )


        asyncio.run(main())
        """
        async with self._raw_client.download_sandbox_file(sandbox_id, path=path, request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk

    @property
    def draft_sessions(self):
        if self._draft_sessions is None:
            from .draft_sessions.client import AsyncDraftSessionsClient  # noqa: E402

            self._draft_sessions = AsyncDraftSessionsClient(client_wrapper=self._client_wrapper)
        return self._draft_sessions

    @property
    def sessions(self):
        if self._sessions is None:
            from .sessions.client import AsyncSessionsClient  # noqa: E402

            self._sessions = AsyncSessionsClient(client_wrapper=self._client_wrapper)
        return self._sessions
