# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from .....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .....types.mcp_server import McpServer
from .....types.model import Model
from .....types.response_format import ResponseFormat
from .....types.runtime_config import RuntimeConfig
from .....types.skill import Skill
from .update_draft_session_request_agent_spec_messages_item import UpdateDraftSessionRequestAgentSpecMessagesItem


class UpdateDraftSessionRequestAgentSpec(UniversalBaseModel):
    """
    Replacement inline spec; never cleared.
    """

    model: Model
    instructions: typing.Optional[str] = None
    messages: typing.Optional[typing.List[UpdateDraftSessionRequestAgentSpecMessagesItem]] = None
    mcp_servers: typing.Optional[typing.List[McpServer]] = None
    response_format: typing.Optional[ResponseFormat] = None
    skills: typing.Optional[typing.List[Skill]] = None
    config: typing.Optional[RuntimeConfig] = None
    variables: typing.Optional[typing.Dict[str, str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
