# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .action_required_event import ActionRequiredEvent
    from .agent_info import AgentInfo
    from .agent_parent import AgentParent
    from .agent_spec import AgentSpec
    from .agent_spec_messages_item import AgentSpecMessagesItem
    from .approval_allow import ApprovalAllow
    from .approval_decision import ApprovalDecision
    from .approval_deny import ApprovalDeny
    from .base_mcp_auth_required_event import BaseMcpAuthRequiredEvent
    from .base_thread_done_event import BaseThreadDoneEvent
    from .chat_completion_chunk_delta_tool_call import ChatCompletionChunkDeltaToolCall
    from .chat_completion_chunk_delta_tool_call_function import ChatCompletionChunkDeltaToolCallFunction
    from .chat_completion_content_part_refusal import ChatCompletionContentPartRefusal
    from .chat_completion_content_part_text import ChatCompletionContentPartText
    from .chat_completion_message_tool_call import ChatCompletionMessageToolCall
    from .chat_completion_message_tool_call_function import ChatCompletionMessageToolCallFunction
    from .draft_session import DraftSession
    from .extended_chunk_delta_tool_call import ExtendedChunkDeltaToolCall
    from .file_upload_content_part import FileUploadContentPart
    from .file_upload_content_part_file import FileUploadContentPartFile
    from .finish_reason import FinishReason
    from .mcp_auth_required_event import McpAuthRequiredEvent
    from .mcp_initialize_event import McpInitializeEvent
    from .mcp_server import McpServer
    from .mcp_server_auth_info import McpServerAuthInfo
    from .mcp_server_disable_tools_item import McpServerDisableToolsItem
    from .mcp_server_enable_tools_item import McpServerEnableToolsItem
    from .mcp_server_init_info import McpServerInitInfo
    from .mcp_server_preload_tools_item import McpServerPreloadToolsItem
    from .mcp_server_require_approval_for_tools_item import McpServerRequireApprovalForToolsItem
    from .mcp_tool_info import McpToolInfo
    from .model import Model
    from .model_message_delta_event import ModelMessageDeltaEvent
    from .model_message_event import ModelMessageEvent
    from .model_message_event_content import ModelMessageEventContent
    from .model_message_event_content_one_item import ModelMessageEventContentOneItem
    from .model_message_usage import ModelMessageUsage
    from .model_message_usage_input_tokens_breakdown import ModelMessageUsageInputTokensBreakdown
    from .model_params import ModelParams
    from .raw_tool_call import RawToolCall
    from .request_error_response import RequestErrorResponse
    from .request_error_response_error import RequestErrorResponseError
    from .response_format import ResponseFormat
    from .response_format_json_schema import ResponseFormatJsonSchema
    from .response_format_json_schema_json_schema import ResponseFormatJsonSchemaJsonSchema
    from .response_format_one import ResponseFormatOne
    from .response_format_zero import ResponseFormatZero
    from .runtime_config import RuntimeConfig
    from .runtime_config_ask_user_questions import RuntimeConfigAskUserQuestions
    from .runtime_config_context_management import RuntimeConfigContextManagement
    from .runtime_config_context_management_compaction import RuntimeConfigContextManagementCompaction
    from .runtime_config_context_management_large_tool_response import RuntimeConfigContextManagementLargeToolResponse
    from .runtime_config_dynamic_sub_agents import RuntimeConfigDynamicSubAgents
    from .runtime_config_generative_ui import RuntimeConfigGenerativeUi
    from .runtime_config_sandbox import RuntimeConfigSandbox
    from .sandbox_created_event import SandboxCreatedEvent
    from .session import Session
    from .skill import Skill
    from .subject import Subject
    from .text_content_part import TextContentPart
    from .thread_created_event import ThreadCreatedEvent
    from .thread_done_event import ThreadDoneEvent
    from .thread_state import ThreadState
    from .thread_state_done import ThreadStateDone
    from .thread_state_error import ThreadStateError
    from .token_pagination import TokenPagination
    from .tool_approval_required_event import ToolApprovalRequiredEvent
    from .tool_call import ToolCall
    from .tool_call_ref import ToolCallRef
    from .tool_info import ToolInfo
    from .tool_response_event import ToolResponseEvent
    from .tool_response_required_event import ToolResponseRequiredEvent
    from .true_foundry_system_tool_info import TrueFoundrySystemToolInfo
    from .turn import Turn
    from .turn_created_event import TurnCreatedEvent
    from .turn_done_event import TurnDoneEvent
    from .turn_done_event_state import TurnDoneEventState
    from .turn_event import TurnEvent
    from .turn_input_item import TurnInputItem
    from .turn_state import TurnState
    from .turn_state_cancelled import TurnStateCancelled
    from .turn_state_cancelled_reason import TurnStateCancelledReason
    from .turn_state_done import TurnStateDone
    from .turn_state_done_output import TurnStateDoneOutput
    from .turn_state_done_output_content import TurnStateDoneOutputContent
    from .turn_state_done_output_content_one_item import TurnStateDoneOutputContentOneItem
    from .turn_state_error import TurnStateError
    from .turn_state_running import TurnStateRunning
    from .turn_streaming_event import TurnStreamingEvent
    from .user_message import UserMessage
    from .user_message_content import UserMessageContent
    from .user_message_content_one_item import UserMessageContentOneItem
    from .user_tool_approval_event import UserToolApprovalEvent
    from .user_tool_response_event import UserToolResponseEvent
_dynamic_imports: typing.Dict[str, str] = {
    "ActionRequiredEvent": ".action_required_event",
    "AgentInfo": ".agent_info",
    "AgentParent": ".agent_parent",
    "AgentSpec": ".agent_spec",
    "AgentSpecMessagesItem": ".agent_spec_messages_item",
    "ApprovalAllow": ".approval_allow",
    "ApprovalDecision": ".approval_decision",
    "ApprovalDeny": ".approval_deny",
    "BaseMcpAuthRequiredEvent": ".base_mcp_auth_required_event",
    "BaseThreadDoneEvent": ".base_thread_done_event",
    "ChatCompletionChunkDeltaToolCall": ".chat_completion_chunk_delta_tool_call",
    "ChatCompletionChunkDeltaToolCallFunction": ".chat_completion_chunk_delta_tool_call_function",
    "ChatCompletionContentPartRefusal": ".chat_completion_content_part_refusal",
    "ChatCompletionContentPartText": ".chat_completion_content_part_text",
    "ChatCompletionMessageToolCall": ".chat_completion_message_tool_call",
    "ChatCompletionMessageToolCallFunction": ".chat_completion_message_tool_call_function",
    "DraftSession": ".draft_session",
    "ExtendedChunkDeltaToolCall": ".extended_chunk_delta_tool_call",
    "FileUploadContentPart": ".file_upload_content_part",
    "FileUploadContentPartFile": ".file_upload_content_part_file",
    "FinishReason": ".finish_reason",
    "McpAuthRequiredEvent": ".mcp_auth_required_event",
    "McpInitializeEvent": ".mcp_initialize_event",
    "McpServer": ".mcp_server",
    "McpServerAuthInfo": ".mcp_server_auth_info",
    "McpServerDisableToolsItem": ".mcp_server_disable_tools_item",
    "McpServerEnableToolsItem": ".mcp_server_enable_tools_item",
    "McpServerInitInfo": ".mcp_server_init_info",
    "McpServerPreloadToolsItem": ".mcp_server_preload_tools_item",
    "McpServerRequireApprovalForToolsItem": ".mcp_server_require_approval_for_tools_item",
    "McpToolInfo": ".mcp_tool_info",
    "Model": ".model",
    "ModelMessageDeltaEvent": ".model_message_delta_event",
    "ModelMessageEvent": ".model_message_event",
    "ModelMessageEventContent": ".model_message_event_content",
    "ModelMessageEventContentOneItem": ".model_message_event_content_one_item",
    "ModelMessageUsage": ".model_message_usage",
    "ModelMessageUsageInputTokensBreakdown": ".model_message_usage_input_tokens_breakdown",
    "ModelParams": ".model_params",
    "RawToolCall": ".raw_tool_call",
    "RequestErrorResponse": ".request_error_response",
    "RequestErrorResponseError": ".request_error_response_error",
    "ResponseFormat": ".response_format",
    "ResponseFormatJsonSchema": ".response_format_json_schema",
    "ResponseFormatJsonSchemaJsonSchema": ".response_format_json_schema_json_schema",
    "ResponseFormatOne": ".response_format_one",
    "ResponseFormatZero": ".response_format_zero",
    "RuntimeConfig": ".runtime_config",
    "RuntimeConfigAskUserQuestions": ".runtime_config_ask_user_questions",
    "RuntimeConfigContextManagement": ".runtime_config_context_management",
    "RuntimeConfigContextManagementCompaction": ".runtime_config_context_management_compaction",
    "RuntimeConfigContextManagementLargeToolResponse": ".runtime_config_context_management_large_tool_response",
    "RuntimeConfigDynamicSubAgents": ".runtime_config_dynamic_sub_agents",
    "RuntimeConfigGenerativeUi": ".runtime_config_generative_ui",
    "RuntimeConfigSandbox": ".runtime_config_sandbox",
    "SandboxCreatedEvent": ".sandbox_created_event",
    "Session": ".session",
    "Skill": ".skill",
    "Subject": ".subject",
    "TextContentPart": ".text_content_part",
    "ThreadCreatedEvent": ".thread_created_event",
    "ThreadDoneEvent": ".thread_done_event",
    "ThreadState": ".thread_state",
    "ThreadStateDone": ".thread_state_done",
    "ThreadStateError": ".thread_state_error",
    "TokenPagination": ".token_pagination",
    "ToolApprovalRequiredEvent": ".tool_approval_required_event",
    "ToolCall": ".tool_call",
    "ToolCallRef": ".tool_call_ref",
    "ToolInfo": ".tool_info",
    "ToolResponseEvent": ".tool_response_event",
    "ToolResponseRequiredEvent": ".tool_response_required_event",
    "TrueFoundrySystemToolInfo": ".true_foundry_system_tool_info",
    "Turn": ".turn",
    "TurnCreatedEvent": ".turn_created_event",
    "TurnDoneEvent": ".turn_done_event",
    "TurnDoneEventState": ".turn_done_event_state",
    "TurnEvent": ".turn_event",
    "TurnInputItem": ".turn_input_item",
    "TurnState": ".turn_state",
    "TurnStateCancelled": ".turn_state_cancelled",
    "TurnStateCancelledReason": ".turn_state_cancelled_reason",
    "TurnStateDone": ".turn_state_done",
    "TurnStateDoneOutput": ".turn_state_done_output",
    "TurnStateDoneOutputContent": ".turn_state_done_output_content",
    "TurnStateDoneOutputContentOneItem": ".turn_state_done_output_content_one_item",
    "TurnStateError": ".turn_state_error",
    "TurnStateRunning": ".turn_state_running",
    "TurnStreamingEvent": ".turn_streaming_event",
    "UserMessage": ".user_message",
    "UserMessageContent": ".user_message_content",
    "UserMessageContentOneItem": ".user_message_content_one_item",
    "UserToolApprovalEvent": ".user_tool_approval_event",
    "UserToolResponseEvent": ".user_tool_response_event",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ActionRequiredEvent",
    "AgentInfo",
    "AgentParent",
    "AgentSpec",
    "AgentSpecMessagesItem",
    "ApprovalAllow",
    "ApprovalDecision",
    "ApprovalDeny",
    "BaseMcpAuthRequiredEvent",
    "BaseThreadDoneEvent",
    "ChatCompletionChunkDeltaToolCall",
    "ChatCompletionChunkDeltaToolCallFunction",
    "ChatCompletionContentPartRefusal",
    "ChatCompletionContentPartText",
    "ChatCompletionMessageToolCall",
    "ChatCompletionMessageToolCallFunction",
    "DraftSession",
    "ExtendedChunkDeltaToolCall",
    "FileUploadContentPart",
    "FileUploadContentPartFile",
    "FinishReason",
    "McpAuthRequiredEvent",
    "McpInitializeEvent",
    "McpServer",
    "McpServerAuthInfo",
    "McpServerDisableToolsItem",
    "McpServerEnableToolsItem",
    "McpServerInitInfo",
    "McpServerPreloadToolsItem",
    "McpServerRequireApprovalForToolsItem",
    "McpToolInfo",
    "Model",
    "ModelMessageDeltaEvent",
    "ModelMessageEvent",
    "ModelMessageEventContent",
    "ModelMessageEventContentOneItem",
    "ModelMessageUsage",
    "ModelMessageUsageInputTokensBreakdown",
    "ModelParams",
    "RawToolCall",
    "RequestErrorResponse",
    "RequestErrorResponseError",
    "ResponseFormat",
    "ResponseFormatJsonSchema",
    "ResponseFormatJsonSchemaJsonSchema",
    "ResponseFormatOne",
    "ResponseFormatZero",
    "RuntimeConfig",
    "RuntimeConfigAskUserQuestions",
    "RuntimeConfigContextManagement",
    "RuntimeConfigContextManagementCompaction",
    "RuntimeConfigContextManagementLargeToolResponse",
    "RuntimeConfigDynamicSubAgents",
    "RuntimeConfigGenerativeUi",
    "RuntimeConfigSandbox",
    "SandboxCreatedEvent",
    "Session",
    "Skill",
    "Subject",
    "TextContentPart",
    "ThreadCreatedEvent",
    "ThreadDoneEvent",
    "ThreadState",
    "ThreadStateDone",
    "ThreadStateError",
    "TokenPagination",
    "ToolApprovalRequiredEvent",
    "ToolCall",
    "ToolCallRef",
    "ToolInfo",
    "ToolResponseEvent",
    "ToolResponseRequiredEvent",
    "TrueFoundrySystemToolInfo",
    "Turn",
    "TurnCreatedEvent",
    "TurnDoneEvent",
    "TurnDoneEventState",
    "TurnEvent",
    "TurnInputItem",
    "TurnState",
    "TurnStateCancelled",
    "TurnStateCancelledReason",
    "TurnStateDone",
    "TurnStateDoneOutput",
    "TurnStateDoneOutputContent",
    "TurnStateDoneOutputContentOneItem",
    "TurnStateError",
    "TurnStateRunning",
    "TurnStreamingEvent",
    "UserMessage",
    "UserMessageContent",
    "UserMessageContentOneItem",
    "UserToolApprovalEvent",
    "UserToolResponseEvent",
]
