# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .action_required_event import ActionRequiredEvent
    from .agent_info import AgentInfo
    from .agent_parent import AgentParent
    from .agent_spec import AgentSpec
    from .agent_spec_user_message import AgentSpecUserMessage
    from .approval_allow import ApprovalAllow
    from .approval_decision import ApprovalDecision
    from .approval_deny import ApprovalDeny
    from .ask_user_questions_config import AskUserQuestionsConfig
    from .base_mcp_auth_required_event import BaseMcpAuthRequiredEvent
    from .base_thread_done_event import BaseThreadDoneEvent
    from .cancel_session_response import CancelSessionResponse
    from .chat_completion_chunk_delta_tool_call import ChatCompletionChunkDeltaToolCall
    from .chat_completion_chunk_delta_tool_call_function import ChatCompletionChunkDeltaToolCallFunction
    from .chat_completion_content_part_refusal import ChatCompletionContentPartRefusal
    from .chat_completion_content_part_text import ChatCompletionContentPartText
    from .chat_completion_message_tool_call import ChatCompletionMessageToolCall
    from .chat_completion_message_tool_call_function import ChatCompletionMessageToolCallFunction
    from .context_management_config import ContextManagementConfig
    from .context_management_config_compaction import ContextManagementConfigCompaction
    from .draft_session import DraftSession
    from .dynamic_sub_agents_config import DynamicSubAgentsConfig
    from .extended_chunk_delta_tool_call import ExtendedChunkDeltaToolCall
    from .file_content import FileContent
    from .finish_reason import FinishReason
    from .generative_ui_config import GenerativeUiConfig
    from .get_draft_session_response import GetDraftSessionResponse
    from .get_session_response import GetSessionResponse
    from .get_turn_response import GetTurnResponse
    from .inline_mcp_server import InlineMcpServer
    from .inline_mcp_server_disable_tools_item import InlineMcpServerDisableToolsItem
    from .inline_mcp_server_enable_tools_item import InlineMcpServerEnableToolsItem
    from .inline_mcp_server_preload_tools_item import InlineMcpServerPreloadToolsItem
    from .inline_mcp_server_require_approval_for_tools_item import InlineMcpServerRequireApprovalForToolsItem
    from .large_tool_response_config import LargeToolResponseConfig
    from .list_draft_sessions_order import ListDraftSessionsOrder
    from .list_draft_sessions_response import ListDraftSessionsResponse
    from .list_events_order import ListEventsOrder
    from .list_events_response import ListEventsResponse
    from .list_owned_sessions_order import ListOwnedSessionsOrder
    from .list_owned_sessions_response import ListOwnedSessionsResponse
    from .list_owned_sessions_response_data_item import ListOwnedSessionsResponseDataItem
    from .list_session_events_response import ListSessionEventsResponse
    from .list_sessions_order import ListSessionsOrder
    from .list_sessions_response import ListSessionsResponse
    from .list_turns_response import ListTurnsResponse
    from .mcp_auth_required_event import McpAuthRequiredEvent
    from .mcp_initialize_event import McpInitializeEvent
    from .mcp_server import McpServer
    from .mcp_server_auth_info import McpServerAuthInfo
    from .mcp_server_init_info import McpServerInitInfo
    from .mcp_server_init_info_transport_type import McpServerInitInfoTransportType
    from .mcp_tool_info import McpToolInfo
    from .model import Model
    from .model_message_delta_event import ModelMessageDeltaEvent
    from .model_message_event import ModelMessageEvent
    from .model_message_event_content import ModelMessageEventContent
    from .model_message_event_content_one_item import ModelMessageEventContentOneItem
    from .model_message_usage import ModelMessageUsage
    from .model_message_usage_input_tokens_breakdown import ModelMessageUsageInputTokensBreakdown
    from .model_params import ModelParams
    from .model_params_cache_control import ModelParamsCacheControl
    from .previous_turn_id_input import PreviousTurnIdInput
    from .raw_tool_call import RawToolCall
    from .registry_mcp_server import RegistryMcpServer
    from .registry_mcp_server_disable_tools_item import RegistryMcpServerDisableToolsItem
    from .registry_mcp_server_enable_tools_item import RegistryMcpServerEnableToolsItem
    from .registry_mcp_server_preload_tools_item import RegistryMcpServerPreloadToolsItem
    from .registry_mcp_server_require_approval_for_tools_item import RegistryMcpServerRequireApprovalForToolsItem
    from .request_error_response import RequestErrorResponse
    from .request_error_response_error import RequestErrorResponseError
    from .response_format import ResponseFormat
    from .response_format_json_schema import ResponseFormatJsonSchema
    from .response_format_json_schema_json_schema import ResponseFormatJsonSchemaJsonSchema
    from .response_format_one import ResponseFormatOne
    from .response_format_zero import ResponseFormatZero
    from .runtime_config import RuntimeConfig
    from .sandbox_config import SandboxConfig
    from .sandbox_created_event import SandboxCreatedEvent
    from .sandbox_network_policy import SandboxNetworkPolicy
    from .sandbox_network_policy_auth_inject_item import SandboxNetworkPolicyAuthInjectItem
    from .sandbox_network_policy_auth_inject_item_auth_data import SandboxNetworkPolicyAuthInjectItemAuthData
    from .sandbox_network_policy_auth_inject_item_match import SandboxNetworkPolicyAuthInjectItemMatch
    from .session import Session
    from .session_event import SessionEvent
    from .session_event_item import SessionEventItem
    from .skill_mount import SkillMount
    from .subject import Subject
    from .text_content import TextContent
    from .thread_created_event import ThreadCreatedEvent
    from .thread_done_event import ThreadDoneEvent
    from .thread_state import ThreadState
    from .thread_state_done import ThreadStateDone
    from .thread_state_error import ThreadStateError
    from .token_pagination import TokenPagination
    from .tool_approval_required_event import ToolApprovalRequiredEvent
    from .tool_call import ToolCall
    from .tool_call_ref import ToolCallRef
    from .tool_info import ToolInfo
    from .tool_response_event import ToolResponseEvent
    from .tool_response_required_event import ToolResponseRequiredEvent
    from .true_foundry_system_tool_info import TrueFoundrySystemToolInfo
    from .turn import Turn
    from .turn_created_event import TurnCreatedEvent
    from .turn_done_event import TurnDoneEvent
    from .turn_done_event_state import TurnDoneEventState
    from .turn_event import TurnEvent
    from .turn_input_item import TurnInputItem
    from .turn_state import TurnState
    from .turn_state_cancelled import TurnStateCancelled
    from .turn_state_cancelled_reason import TurnStateCancelledReason
    from .turn_state_done import TurnStateDone
    from .turn_state_done_output import TurnStateDoneOutput
    from .turn_state_done_output_content import TurnStateDoneOutputContent
    from .turn_state_done_output_content_one_item import TurnStateDoneOutputContentOneItem
    from .turn_state_error import TurnStateError
    from .turn_state_running import TurnStateRunning
    from .turn_streaming_event import TurnStreamingEvent
    from .user_message import UserMessage
    from .user_message_content import UserMessageContent
    from .user_message_content_item import UserMessageContentItem
    from .user_tool_approval_event import UserToolApprovalEvent
    from .user_tool_response_event import UserToolResponseEvent
_dynamic_imports: typing.Dict[str, str] = {
    "ActionRequiredEvent": ".action_required_event",
    "AgentInfo": ".agent_info",
    "AgentParent": ".agent_parent",
    "AgentSpec": ".agent_spec",
    "AgentSpecUserMessage": ".agent_spec_user_message",
    "ApprovalAllow": ".approval_allow",
    "ApprovalDecision": ".approval_decision",
    "ApprovalDeny": ".approval_deny",
    "AskUserQuestionsConfig": ".ask_user_questions_config",
    "BaseMcpAuthRequiredEvent": ".base_mcp_auth_required_event",
    "BaseThreadDoneEvent": ".base_thread_done_event",
    "CancelSessionResponse": ".cancel_session_response",
    "ChatCompletionChunkDeltaToolCall": ".chat_completion_chunk_delta_tool_call",
    "ChatCompletionChunkDeltaToolCallFunction": ".chat_completion_chunk_delta_tool_call_function",
    "ChatCompletionContentPartRefusal": ".chat_completion_content_part_refusal",
    "ChatCompletionContentPartText": ".chat_completion_content_part_text",
    "ChatCompletionMessageToolCall": ".chat_completion_message_tool_call",
    "ChatCompletionMessageToolCallFunction": ".chat_completion_message_tool_call_function",
    "ContextManagementConfig": ".context_management_config",
    "ContextManagementConfigCompaction": ".context_management_config_compaction",
    "DraftSession": ".draft_session",
    "DynamicSubAgentsConfig": ".dynamic_sub_agents_config",
    "ExtendedChunkDeltaToolCall": ".extended_chunk_delta_tool_call",
    "FileContent": ".file_content",
    "FinishReason": ".finish_reason",
    "GenerativeUiConfig": ".generative_ui_config",
    "GetDraftSessionResponse": ".get_draft_session_response",
    "GetSessionResponse": ".get_session_response",
    "GetTurnResponse": ".get_turn_response",
    "InlineMcpServer": ".inline_mcp_server",
    "InlineMcpServerDisableToolsItem": ".inline_mcp_server_disable_tools_item",
    "InlineMcpServerEnableToolsItem": ".inline_mcp_server_enable_tools_item",
    "InlineMcpServerPreloadToolsItem": ".inline_mcp_server_preload_tools_item",
    "InlineMcpServerRequireApprovalForToolsItem": ".inline_mcp_server_require_approval_for_tools_item",
    "LargeToolResponseConfig": ".large_tool_response_config",
    "ListDraftSessionsOrder": ".list_draft_sessions_order",
    "ListDraftSessionsResponse": ".list_draft_sessions_response",
    "ListEventsOrder": ".list_events_order",
    "ListEventsResponse": ".list_events_response",
    "ListOwnedSessionsOrder": ".list_owned_sessions_order",
    "ListOwnedSessionsResponse": ".list_owned_sessions_response",
    "ListOwnedSessionsResponseDataItem": ".list_owned_sessions_response_data_item",
    "ListSessionEventsResponse": ".list_session_events_response",
    "ListSessionsOrder": ".list_sessions_order",
    "ListSessionsResponse": ".list_sessions_response",
    "ListTurnsResponse": ".list_turns_response",
    "McpAuthRequiredEvent": ".mcp_auth_required_event",
    "McpInitializeEvent": ".mcp_initialize_event",
    "McpServer": ".mcp_server",
    "McpServerAuthInfo": ".mcp_server_auth_info",
    "McpServerInitInfo": ".mcp_server_init_info",
    "McpServerInitInfoTransportType": ".mcp_server_init_info_transport_type",
    "McpToolInfo": ".mcp_tool_info",
    "Model": ".model",
    "ModelMessageDeltaEvent": ".model_message_delta_event",
    "ModelMessageEvent": ".model_message_event",
    "ModelMessageEventContent": ".model_message_event_content",
    "ModelMessageEventContentOneItem": ".model_message_event_content_one_item",
    "ModelMessageUsage": ".model_message_usage",
    "ModelMessageUsageInputTokensBreakdown": ".model_message_usage_input_tokens_breakdown",
    "ModelParams": ".model_params",
    "ModelParamsCacheControl": ".model_params_cache_control",
    "PreviousTurnIdInput": ".previous_turn_id_input",
    "RawToolCall": ".raw_tool_call",
    "RegistryMcpServer": ".registry_mcp_server",
    "RegistryMcpServerDisableToolsItem": ".registry_mcp_server_disable_tools_item",
    "RegistryMcpServerEnableToolsItem": ".registry_mcp_server_enable_tools_item",
    "RegistryMcpServerPreloadToolsItem": ".registry_mcp_server_preload_tools_item",
    "RegistryMcpServerRequireApprovalForToolsItem": ".registry_mcp_server_require_approval_for_tools_item",
    "RequestErrorResponse": ".request_error_response",
    "RequestErrorResponseError": ".request_error_response_error",
    "ResponseFormat": ".response_format",
    "ResponseFormatJsonSchema": ".response_format_json_schema",
    "ResponseFormatJsonSchemaJsonSchema": ".response_format_json_schema_json_schema",
    "ResponseFormatOne": ".response_format_one",
    "ResponseFormatZero": ".response_format_zero",
    "RuntimeConfig": ".runtime_config",
    "SandboxConfig": ".sandbox_config",
    "SandboxCreatedEvent": ".sandbox_created_event",
    "SandboxNetworkPolicy": ".sandbox_network_policy",
    "SandboxNetworkPolicyAuthInjectItem": ".sandbox_network_policy_auth_inject_item",
    "SandboxNetworkPolicyAuthInjectItemAuthData": ".sandbox_network_policy_auth_inject_item_auth_data",
    "SandboxNetworkPolicyAuthInjectItemMatch": ".sandbox_network_policy_auth_inject_item_match",
    "Session": ".session",
    "SessionEvent": ".session_event",
    "SessionEventItem": ".session_event_item",
    "SkillMount": ".skill_mount",
    "Subject": ".subject",
    "TextContent": ".text_content",
    "ThreadCreatedEvent": ".thread_created_event",
    "ThreadDoneEvent": ".thread_done_event",
    "ThreadState": ".thread_state",
    "ThreadStateDone": ".thread_state_done",
    "ThreadStateError": ".thread_state_error",
    "TokenPagination": ".token_pagination",
    "ToolApprovalRequiredEvent": ".tool_approval_required_event",
    "ToolCall": ".tool_call",
    "ToolCallRef": ".tool_call_ref",
    "ToolInfo": ".tool_info",
    "ToolResponseEvent": ".tool_response_event",
    "ToolResponseRequiredEvent": ".tool_response_required_event",
    "TrueFoundrySystemToolInfo": ".true_foundry_system_tool_info",
    "Turn": ".turn",
    "TurnCreatedEvent": ".turn_created_event",
    "TurnDoneEvent": ".turn_done_event",
    "TurnDoneEventState": ".turn_done_event_state",
    "TurnEvent": ".turn_event",
    "TurnInputItem": ".turn_input_item",
    "TurnState": ".turn_state",
    "TurnStateCancelled": ".turn_state_cancelled",
    "TurnStateCancelledReason": ".turn_state_cancelled_reason",
    "TurnStateDone": ".turn_state_done",
    "TurnStateDoneOutput": ".turn_state_done_output",
    "TurnStateDoneOutputContent": ".turn_state_done_output_content",
    "TurnStateDoneOutputContentOneItem": ".turn_state_done_output_content_one_item",
    "TurnStateError": ".turn_state_error",
    "TurnStateRunning": ".turn_state_running",
    "TurnStreamingEvent": ".turn_streaming_event",
    "UserMessage": ".user_message",
    "UserMessageContent": ".user_message_content",
    "UserMessageContentItem": ".user_message_content_item",
    "UserToolApprovalEvent": ".user_tool_approval_event",
    "UserToolResponseEvent": ".user_tool_response_event",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ActionRequiredEvent",
    "AgentInfo",
    "AgentParent",
    "AgentSpec",
    "AgentSpecUserMessage",
    "ApprovalAllow",
    "ApprovalDecision",
    "ApprovalDeny",
    "AskUserQuestionsConfig",
    "BaseMcpAuthRequiredEvent",
    "BaseThreadDoneEvent",
    "CancelSessionResponse",
    "ChatCompletionChunkDeltaToolCall",
    "ChatCompletionChunkDeltaToolCallFunction",
    "ChatCompletionContentPartRefusal",
    "ChatCompletionContentPartText",
    "ChatCompletionMessageToolCall",
    "ChatCompletionMessageToolCallFunction",
    "ContextManagementConfig",
    "ContextManagementConfigCompaction",
    "DraftSession",
    "DynamicSubAgentsConfig",
    "ExtendedChunkDeltaToolCall",
    "FileContent",
    "FinishReason",
    "GenerativeUiConfig",
    "GetDraftSessionResponse",
    "GetSessionResponse",
    "GetTurnResponse",
    "InlineMcpServer",
    "InlineMcpServerDisableToolsItem",
    "InlineMcpServerEnableToolsItem",
    "InlineMcpServerPreloadToolsItem",
    "InlineMcpServerRequireApprovalForToolsItem",
    "LargeToolResponseConfig",
    "ListDraftSessionsOrder",
    "ListDraftSessionsResponse",
    "ListEventsOrder",
    "ListEventsResponse",
    "ListOwnedSessionsOrder",
    "ListOwnedSessionsResponse",
    "ListOwnedSessionsResponseDataItem",
    "ListSessionEventsResponse",
    "ListSessionsOrder",
    "ListSessionsResponse",
    "ListTurnsResponse",
    "McpAuthRequiredEvent",
    "McpInitializeEvent",
    "McpServer",
    "McpServerAuthInfo",
    "McpServerInitInfo",
    "McpServerInitInfoTransportType",
    "McpToolInfo",
    "Model",
    "ModelMessageDeltaEvent",
    "ModelMessageEvent",
    "ModelMessageEventContent",
    "ModelMessageEventContentOneItem",
    "ModelMessageUsage",
    "ModelMessageUsageInputTokensBreakdown",
    "ModelParams",
    "ModelParamsCacheControl",
    "PreviousTurnIdInput",
    "RawToolCall",
    "RegistryMcpServer",
    "RegistryMcpServerDisableToolsItem",
    "RegistryMcpServerEnableToolsItem",
    "RegistryMcpServerPreloadToolsItem",
    "RegistryMcpServerRequireApprovalForToolsItem",
    "RequestErrorResponse",
    "RequestErrorResponseError",
    "ResponseFormat",
    "ResponseFormatJsonSchema",
    "ResponseFormatJsonSchemaJsonSchema",
    "ResponseFormatOne",
    "ResponseFormatZero",
    "RuntimeConfig",
    "SandboxConfig",
    "SandboxCreatedEvent",
    "SandboxNetworkPolicy",
    "SandboxNetworkPolicyAuthInjectItem",
    "SandboxNetworkPolicyAuthInjectItemAuthData",
    "SandboxNetworkPolicyAuthInjectItemMatch",
    "Session",
    "SessionEvent",
    "SessionEventItem",
    "SkillMount",
    "Subject",
    "TextContent",
    "ThreadCreatedEvent",
    "ThreadDoneEvent",
    "ThreadState",
    "ThreadStateDone",
    "ThreadStateError",
    "TokenPagination",
    "ToolApprovalRequiredEvent",
    "ToolCall",
    "ToolCallRef",
    "ToolInfo",
    "ToolResponseEvent",
    "ToolResponseRequiredEvent",
    "TrueFoundrySystemToolInfo",
    "Turn",
    "TurnCreatedEvent",
    "TurnDoneEvent",
    "TurnDoneEventState",
    "TurnEvent",
    "TurnInputItem",
    "TurnState",
    "TurnStateCancelled",
    "TurnStateCancelledReason",
    "TurnStateDone",
    "TurnStateDoneOutput",
    "TurnStateDoneOutputContent",
    "TurnStateDoneOutputContentOneItem",
    "TurnStateError",
    "TurnStateRunning",
    "TurnStreamingEvent",
    "UserMessage",
    "UserMessageContent",
    "UserMessageContentItem",
    "UserToolApprovalEvent",
    "UserToolResponseEvent",
]
