# This file was auto-generated by Fern from our API Definition.

import typing

from .mcp_auth_required_event import McpAuthRequiredEvent
from .tool_approval_required_event import ToolApprovalRequiredEvent
from .tool_response_required_event import ToolResponseRequiredEvent

ActionRequiredEvent = typing.Union[ToolApprovalRequiredEvent, ToolResponseRequiredEvent, McpAuthRequiredEvent]
