# This file was auto-generated by Fern from our API Definition.

import typing

from .agent_enriched_assistant_message import AgentEnrichedAssistantMessage
from .agent_llm_tool_message import AgentLlmToolMessage
from .agent_llm_user_message import AgentLlmUserMessage
from .agent_persisted_approval_decision_message import AgentPersistedApprovalDecisionMessage

AgentExecutionOverwriteContextContextItem = typing.Union[
    AgentLlmUserMessage, AgentEnrichedAssistantMessage, AgentLlmToolMessage, AgentPersistedApprovalDecisionMessage
]
