# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_response_done_cancellation_reason_cancellation_reason import (
    AgentResponseDoneCancellationReasonCancellationReason,
)


class AgentResponseDoneCancellationReason(UniversalBaseModel):
    type: typing.Literal["response.done"] = "response.done"
    status: typing.Literal["cancelled"] = "cancelled"
    cancellation_reason: AgentResponseDoneCancellationReasonCancellationReason

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
