# This file was auto-generated by Fern from our API Definition.

import typing

AgentMcpServerRequestRequireApprovalForToolsItem = typing.Union[
    typing.Literal["@all"], typing.Literal["@write"], typing.Literal["@destructive"], str
]
