# This file was auto-generated by Fern from our API Definition.

import typing

from .agent_mcp_tool_call_info import AgentMcpToolCallInfo
from .agent_true_foundry_system_tool_call_info import AgentTrueFoundrySystemToolCallInfo

AgentExtendedDeltaToolCallToolInfo = typing.Union[AgentTrueFoundrySystemToolCallInfo, AgentMcpToolCallInfo]
