# This file was auto-generated by Fern from our API Definition.

import typing

from .agent_approval_or_tool_response_message import AgentApprovalOrToolResponseMessage
from .agent_input_user_message import AgentInputUserMessage

AgentResponsesStatefulInput = typing.Union[
    typing.List[AgentInputUserMessage], typing.List[AgentApprovalOrToolResponseMessage]
]
