# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_internal_enriched_assistant_message_audio import AgentInternalEnrichedAssistantMessageAudio
from .agent_internal_enriched_assistant_message_content import AgentInternalEnrichedAssistantMessageContent
from .agent_internal_enriched_assistant_message_function_call import AgentInternalEnrichedAssistantMessageFunctionCall
from .agent_internal_enriched_assistant_message_thinking_blocks_item import (
    AgentInternalEnrichedAssistantMessageThinkingBlocksItem,
)
from .agent_internal_enriched_tool_call import AgentInternalEnrichedToolCall


class AgentInternalEnrichedAssistantMessage(UniversalBaseModel):
    role: typing.Literal["assistant"] = "assistant"
    audio: typing.Optional[AgentInternalEnrichedAssistantMessageAudio] = None
    content: typing.Optional[AgentInternalEnrichedAssistantMessageContent] = None
    function_call: typing.Optional[AgentInternalEnrichedAssistantMessageFunctionCall] = None
    name: typing.Optional[str] = None
    refusal: typing.Optional[str] = None
    thinking_blocks: typing.Optional[typing.List[AgentInternalEnrichedAssistantMessageThinkingBlocksItem]] = None
    tool_calls: typing.Optional[typing.List[AgentInternalEnrichedToolCall]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
