# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .agent_extended_delta_tool_call_tool_info import AgentExtendedDeltaToolCallToolInfo
from .chat_completion_chunk_delta_tool_call import ChatCompletionChunkDeltaToolCall


class AgentExtendedDeltaToolCall(ChatCompletionChunkDeltaToolCall):
    tool_info: typing.Optional[AgentExtendedDeltaToolCallToolInfo] = None
    provider_specific_fields: typing.Optional[typing.Dict[str, typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
