# This file was auto-generated by Fern from our API Definition.

import typing

from .agent_input_user_message_content_one_item import AgentInputUserMessageContentOneItem

AgentInputUserMessageContent = typing.Union[str, typing.List[AgentInputUserMessageContentOneItem]]
