# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .agent_internal_tool_call_info import AgentInternalToolCallInfo
from .agent_raw_tool_call import AgentRawToolCall


class AgentInternalEnrichedToolCall(AgentRawToolCall):
    tool_info: AgentInternalToolCallInfo

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
