# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_extended_delta_function_call import AgentExtendedDeltaFunctionCall
from .agent_extended_delta_role import AgentExtendedDeltaRole
from .agent_extended_delta_thinking_blocks_item import AgentExtendedDeltaThinkingBlocksItem
from .agent_extended_delta_tool_call import AgentExtendedDeltaToolCall


class AgentExtendedDelta(UniversalBaseModel):
    content: typing.Optional[str] = None
    refusal: typing.Optional[str] = None
    role: typing.Optional[AgentExtendedDeltaRole] = None
    function_call: typing.Optional[AgentExtendedDeltaFunctionCall] = None
    tool_calls: typing.Optional[typing.List[AgentExtendedDeltaToolCall]] = None
    thinking_blocks: typing.Optional[typing.List[AgentExtendedDeltaThinkingBlocksItem]] = None
    reasoning_content: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
