# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_enriched_assistant_message_audio import AgentEnrichedAssistantMessageAudio
from .agent_enriched_assistant_message_content import AgentEnrichedAssistantMessageContent
from .agent_enriched_assistant_message_function_call import AgentEnrichedAssistantMessageFunctionCall
from .agent_enriched_assistant_message_thinking_blocks_item import AgentEnrichedAssistantMessageThinkingBlocksItem
from .agent_enriched_tool_call import AgentEnrichedToolCall


class AgentEnrichedAssistantMessage(UniversalBaseModel):
    role: typing.Literal["assistant"] = "assistant"
    audio: typing.Optional[AgentEnrichedAssistantMessageAudio] = None
    content: typing.Optional[AgentEnrichedAssistantMessageContent] = None
    function_call: typing.Optional[AgentEnrichedAssistantMessageFunctionCall] = None
    name: typing.Optional[str] = None
    refusal: typing.Optional[str] = None
    thinking_blocks: typing.Optional[typing.List[AgentEnrichedAssistantMessageThinkingBlocksItem]] = None
    tool_calls: typing.Optional[typing.List[AgentEnrichedToolCall]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
