# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_assistant_message import AgentAssistantMessage
from .agent_parent import AgentParent


class AgentExecutionError(UniversalBaseModel):
    type: typing.Literal["agent.error"] = "agent.error"
    execution_id: str
    parent: typing.Optional[AgentParent] = None
    message: str
    output: typing.Optional[AgentAssistantMessage] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
