# This file was auto-generated by Fern from our API Definition.

import typing

from .agent_response_done_cancellation_reason import AgentResponseDoneCancellationReason
from .agent_response_done_error import AgentResponseDoneError
from .agent_response_done_zero import AgentResponseDoneZero

AgentResponseDone = typing.Union[AgentResponseDoneZero, AgentResponseDoneCancellationReason, AgentResponseDoneError]
