# This file was auto-generated by Fern from our API Definition.

import typing

from .chat_completion_content_part_refusal import ChatCompletionContentPartRefusal
from .chat_completion_content_part_text import ChatCompletionContentPartText

AgentInternalEnrichedAssistantMessageContentOneItem = typing.Union[
    ChatCompletionContentPartText, ChatCompletionContentPartRefusal
]
