# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AgentMcpToolCallInfo(UniversalBaseModel):
    mcp_server_id: str
    mcp_server_name: str
    original_tool_name: str
    is_approval_required: typing.Optional[bool] = None
    is_deferred: typing.Optional[bool] = None
    is_client_side: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
