# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_assistant_message import AgentAssistantMessage


class AgentResponseDoneError(UniversalBaseModel):
    type: typing.Literal["response.done"] = "response.done"
    status: typing.Literal["error"] = "error"
    message: str
    output: typing.Optional[AgentAssistantMessage] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
