# This file was auto-generated by Fern from our API Definition.

import typing

from .agent_approval_decision_allow import AgentApprovalDecisionAllow
from .agent_approval_decision_deny import AgentApprovalDecisionDeny

AgentApprovalDecision = typing.Union[AgentApprovalDecisionAllow, AgentApprovalDecisionDeny]
