# This file was auto-generated by Fern from our API Definition.

import typing

from .agent_internal_enriched_assistant_message_content_one_item import (
    AgentInternalEnrichedAssistantMessageContentOneItem,
)

AgentInternalEnrichedAssistantMessageContent = typing.Union[
    str, typing.List[AgentInternalEnrichedAssistantMessageContentOneItem]
]
