# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_mcp_server_request import AgentMcpServerRequest
from .agent_model_params import AgentModelParams
from .agent_responses_format import AgentResponsesFormat
from .agent_responses_inline_agent_messages_item import AgentResponsesInlineAgentMessagesItem
from .agent_responses_inline_agent_sandbox import AgentResponsesInlineAgentSandbox
from .agent_responses_stateful_input import AgentResponsesStatefulInput
from .agent_skill_mount import AgentSkillMount


class AgentResponsesInlineAgent(UniversalBaseModel):
    model: str
    instruction: typing.Optional[str] = None
    messages: typing.Optional[typing.List[AgentResponsesInlineAgentMessagesItem]] = None
    mcp_servers: typing.Optional[typing.List[AgentMcpServerRequest]] = None
    model_params: typing.Optional[AgentModelParams] = None
    response_format: typing.Optional[AgentResponsesFormat] = None
    iteration_limit: typing.Optional[int] = None
    skills: typing.Optional[typing.List[AgentSkillMount]] = None
    sandbox: typing.Optional[AgentResponsesInlineAgentSandbox] = None
    variables: typing.Optional[typing.Dict[str, str]] = None
    previous_response_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of a prior stored response. Pass to continue a stateful conversation.
    """

    input: typing.Optional[AgentResponsesStatefulInput] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
