# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_config_context_management_compaction import AgentConfigContextManagementCompaction
from .agent_config_context_management_large_tool_response import AgentConfigContextManagementLargeToolResponse


class AgentConfigContextManagement(UniversalBaseModel):
    compaction: AgentConfigContextManagementCompaction
    large_tool_response: AgentConfigContextManagementLargeToolResponse

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
