# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class AgentExtendedDeltaRole(enum.StrEnum):
    DEVELOPER = "developer"
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"
    _UNKNOWN = "__AGENTEXTENDEDDELTAROLE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "AgentExtendedDeltaRole":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        developer: typing.Callable[[], T_Result],
        system: typing.Callable[[], T_Result],
        user: typing.Callable[[], T_Result],
        assistant: typing.Callable[[], T_Result],
        tool: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is AgentExtendedDeltaRole.DEVELOPER:
            return developer()
        if self is AgentExtendedDeltaRole.SYSTEM:
            return system()
        if self is AgentExtendedDeltaRole.USER:
            return user()
        if self is AgentExtendedDeltaRole.ASSISTANT:
            return assistant()
        if self is AgentExtendedDeltaRole.TOOL:
            return tool()
        return _unknown_member(self._value_)
