# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_mcp_tool import AgentMcpTool


class AgentMcpServerRequest(UniversalBaseModel):
    name: str
    headers: typing.Optional[typing.Dict[str, str]] = None
    enable_all_tools: bool = True
    tools: typing.Optional[typing.List[AgentMcpTool]] = None
    deferred: bool = False

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
