# This file was auto-generated by Fern from our API Definition.

import typing

from .agent_file_upload_content_part import AgentFileUploadContentPart
from .agent_text_content_part import AgentTextContentPart

AgentInputUserMessageContentOneItem = typing.Union[AgentTextContentPart, AgentFileUploadContentPart]
