# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_responses_stateful_input import AgentResponsesStatefulInput


class AgentResponsesSavedAgent(UniversalBaseModel):
    agent_name: str
    variables: typing.Optional[typing.Dict[str, str]] = None
    previous_response_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of a prior stored response. Pass to continue a stateful conversation.
    """

    input: typing.Optional[AgentResponsesStatefulInput] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
