# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_tool_call_ref import AgentToolCallRef


class AgentToolResponseRequired(UniversalBaseModel):
    type: typing.Literal["tool.response_required"] = "tool.response_required"
    execution_id: str
    tool_calls: typing.List[AgentToolCallRef]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
