# This file was auto-generated by Fern from our API Definition.

import typing

from .agent_approval_decision_message import AgentApprovalDecisionMessage
from .agent_client_side_tool_response_message import AgentClientSideToolResponseMessage

AgentApprovalOrToolResponseMessage = typing.Union[AgentApprovalDecisionMessage, AgentClientSideToolResponseMessage]
