# This file was auto-generated by Fern from our API Definition.

import typing

from .agent_responses_inline_agent import AgentResponsesInlineAgent
from .agent_responses_named_agent import AgentResponsesNamedAgent

AgentResponsesBody = typing.Union[AgentResponsesInlineAgent, AgentResponsesNamedAgent]
