# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .agent_llm_tool_message import AgentLlmToolMessage


class AgentToolMessage(AgentLlmToolMessage):
    type: typing.Literal["agent.message"] = "agent.message"
    execution_id: str
    created_at: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
