# This file was auto-generated by Fern from our API Definition.

import typing

from .inline_agent_run_input import InlineAgentRunInput
from .named_agent_run_input import NamedAgentRunInput

AgentRunInput = typing.Union[NamedAgentRunInput, InlineAgentRunInput]
