# This file was auto-generated by Fern from our API Definition.

import typing

from .approval_allow import ApprovalAllow
from .approval_deny import ApprovalDeny

ApprovalDecision = typing.Union[ApprovalAllow, ApprovalDeny]
