# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .require_approval_tool_selector_item import RequireApprovalToolSelectorItem
from .tools_selector_item import ToolsSelectorItem


class BaseMcpServer(UniversalBaseModel):
    name: str
    enable_tools: typing.Optional[typing.List[ToolsSelectorItem]] = None
    disable_tools: typing.Optional[typing.List[ToolsSelectorItem]] = None
    preload_tools: typing.Optional[typing.List[ToolsSelectorItem]] = None
    require_approval_for_tools: typing.Optional[typing.List[RequireApprovalToolSelectorItem]] = None
    preload: typing.Optional[bool] = False

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
