# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .chat_completion_content_part_input_audio_input_audio import ChatCompletionContentPartInputAudioInputAudio


class ChatCompletionContentPartInputAudio(UniversalBaseModel):
    type: typing.Literal["input_audio"] = "input_audio"
    input_audio: ChatCompletionContentPartInputAudioInputAudio

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
