# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .chat_completion_content_part_image_image_url import ChatCompletionContentPartImageImageUrl


class ChatCompletionContentPartImage(UniversalBaseModel):
    type: typing.Literal["image_url"] = "image_url"
    image_url: ChatCompletionContentPartImageImageUrl

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
