# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .chat_completion_chunk_delta_tool_call_function import ChatCompletionChunkDeltaToolCallFunction
from .chat_completion_chunk_delta_tool_call_type import ChatCompletionChunkDeltaToolCallType


class ChatCompletionChunkDeltaToolCall(UniversalBaseModel):
    index: int
    id: typing.Optional[str] = None
    type: typing.Optional[ChatCompletionChunkDeltaToolCallType] = None
    function: typing.Optional[ChatCompletionChunkDeltaToolCallFunction] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
