# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_spec import AgentSpec
from .draft_session_type import DraftSessionType
from .subject import Subject


class DraftSession(UniversalBaseModel):
    type: DraftSessionType = pydantic.Field()
    """
    Discriminates a draft session from a saved session.
    """

    id: str
    agent_spec: AgentSpec
    agent_name: typing.Optional[str] = None
    title: typing.Optional[str] = None
    created_by_subject: Subject
    created_at: str
    updated_at: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
