# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_config import AgentConfig
from .agent_mcp_server_request import AgentMcpServerRequest
from .agent_model_spec import AgentModelSpec
from .agent_responses_format import AgentResponsesFormat
from .agent_skill_mount import AgentSkillMount
from .draft_session_agent_spec_messages_item import DraftSessionAgentSpecMessagesItem


class DraftSessionAgentSpec(UniversalBaseModel):
    model: AgentModelSpec
    instructions: typing.Optional[str] = None
    messages: typing.Optional[typing.List[DraftSessionAgentSpecMessagesItem]] = None
    mcp_servers: typing.Optional[typing.List[AgentMcpServerRequest]] = None
    response_format: typing.Optional[AgentResponsesFormat] = None
    skills: typing.Optional[typing.List[AgentSkillMount]] = None
    config: typing.Optional[AgentConfig] = None
    variables: typing.Optional[typing.Dict[str, str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
