# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .draft_session_agent_spec import DraftSessionAgentSpec
from .session_subject import SessionSubject


class DraftSession(UniversalBaseModel):
    id: str
    agent_spec: DraftSessionAgentSpec
    agent_name: typing.Optional[str] = None
    title: typing.Optional[str] = None
    created_by_subject: SessionSubject
    created_at: str
    updated_at: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
