# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_conversation_input_message import AgentConversationInputMessage
from .agent_mcp_server_request import AgentMcpServerRequest
from .agent_model_params import AgentModelParams
from .agent_response_format import AgentResponseFormat
from .agent_skill_mount import AgentSkillMount
from .agent_sub_agent import AgentSubAgent
from .inline_agent_run_input_messages_item import InlineAgentRunInputMessagesItem
from .inline_agent_run_input_sandbox import InlineAgentRunInputSandbox


class InlineAgentRunInput(UniversalBaseModel):
    previous_response_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of a prior stored response. Pass to continue a stateful conversation.
    """

    variables: typing.Optional[typing.Dict[str, str]] = None
    skills: typing.Optional[typing.List[AgentSkillMount]] = None
    model: str
    instruction: typing.Optional[str] = None
    messages: typing.Optional[typing.List[InlineAgentRunInputMessagesItem]] = None
    mcp_servers: typing.Optional[typing.List[AgentMcpServerRequest]] = None
    sub_agents: typing.Optional[typing.List[AgentSubAgent]] = None
    model_params: typing.Optional[AgentModelParams] = None
    response_format: typing.Optional[AgentResponseFormat] = None
    iteration_limit: typing.Optional[int] = None
    sandbox: typing.Optional[InlineAgentRunInputSandbox] = None
    input: typing.Optional[typing.List[AgentConversationInputMessage]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
