# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_spec import AgentSpec
from .subject import Subject


class ListOwnedSessionsResponseDataItem_Session(UniversalBaseModel):
    type: typing.Literal["session"] = "session"
    id: str
    agent_name: str
    title: typing.Optional[str] = None
    created_by_subject: Subject
    created_at: str
    updated_at: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow


class ListOwnedSessionsResponseDataItem_SessionDraft(UniversalBaseModel):
    type: typing.Literal["session/draft"] = "session/draft"
    id: str
    agent_spec: AgentSpec
    agent_name: typing.Optional[str] = None
    title: typing.Optional[str] = None
    created_by_subject: Subject
    created_at: str
    updated_at: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow


ListOwnedSessionsResponseDataItem = typing_extensions.Annotated[
    typing.Union[ListOwnedSessionsResponseDataItem_Session, ListOwnedSessionsResponseDataItem_SessionDraft],
    pydantic.Field(discriminator="type"),
]
