# This file was auto-generated by Fern from our API Definition.

import typing

from .inline_mcp_server import InlineMcpServer
from .registry_mcp_server import RegistryMcpServer

McpServer = typing.Union[RegistryMcpServer, InlineMcpServer]
