# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .base_mcp_auth_required_event import BaseMcpAuthRequiredEvent
from .mcp_server_auth_info import McpServerAuthInfo


class McpAuthRequiredEvent(BaseMcpAuthRequiredEvent):
    mcp_servers: typing.List[McpServerAuthInfo]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
