# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .mcp_initialization_info import McpInitializationInfo


class McpInitializeEvent(UniversalBaseModel):
    type: typing.Literal["mcp.initialize"] = "mcp.initialize"
    id: str = pydantic.Field()
    """
    Unique identifier for the event
    """

    created_at: str
    thread_id: str
    content: typing.List[McpInitializationInfo]
    sequence_number: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
