# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_extended_delta_tool_call import AgentExtendedDeltaToolCall
from .agent_finish_reason import AgentFinishReason
from .model_message_delta_event_function_call import ModelMessageDeltaEventFunctionCall
from .model_message_delta_event_thinking_blocks_item import ModelMessageDeltaEventThinkingBlocksItem


class ModelMessageDeltaEvent(UniversalBaseModel):
    content: typing.Optional[str] = None
    refusal: typing.Optional[str] = None
    function_call: typing.Optional[ModelMessageDeltaEventFunctionCall] = None
    tool_calls: typing.Optional[typing.List[AgentExtendedDeltaToolCall]] = None
    thinking_blocks: typing.Optional[typing.List[ModelMessageDeltaEventThinkingBlocksItem]] = None
    reasoning_content: typing.Optional[str] = None
    type: typing.Literal["model.message.delta"] = "model.message.delta"
    id: str = pydantic.Field()
    """
    Unique identifier for the event
    """

    thread_id: str
    created_at: typing.Optional[str] = None
    finish_reason: typing.Optional[AgentFinishReason] = None
    sequence_number: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
