# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .model_params_cache_control import ModelParamsCacheControl


class ModelParams(UniversalBaseModel):
    max_tokens: typing.Optional[float] = None
    temperature: typing.Optional[float] = None
    top_p: typing.Optional[float] = None
    top_k: typing.Optional[float] = None
    parallel_tool_calls: typing.Optional[bool] = None
    reasoning_effort: typing.Optional[str] = None
    cache_control: typing.Optional[ModelParamsCacheControl] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
