# This file was auto-generated by Fern from our API Definition.

import typing

from .agent_redacted_thinking_block import AgentRedactedThinkingBlock
from .agent_thinking_block import AgentThinkingBlock

ModelMessageDeltaEventThinkingBlocksItem = typing.Union[AgentThinkingBlock, AgentRedactedThinkingBlock]
