# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .finish_reason import FinishReason
from .model_message_event_audio import ModelMessageEventAudio
from .model_message_event_content import ModelMessageEventContent
from .model_message_event_function_call import ModelMessageEventFunctionCall
from .model_message_event_thinking_blocks_item import ModelMessageEventThinkingBlocksItem
from .model_message_event_usage import ModelMessageEventUsage
from .tool_call import ToolCall


class ModelMessageEvent(UniversalBaseModel):
    audio: typing.Optional[ModelMessageEventAudio] = None
    content: typing.Optional[ModelMessageEventContent] = None
    function_call: typing.Optional[ModelMessageEventFunctionCall] = None
    name: typing.Optional[str] = None
    refusal: typing.Optional[str] = None
    thinking_blocks: typing.Optional[typing.List[ModelMessageEventThinkingBlocksItem]] = None
    tool_calls: typing.Optional[typing.List[ToolCall]] = None
    type: typing.Literal["model.message"] = "model.message"
    id: str = pydantic.Field()
    """
    Unique identifier for the event
    """

    thread_id: str
    finish_reason: typing.Optional[FinishReason] = None
    created_at: str
    usage: typing.Optional[ModelMessageEventUsage] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
