# This file was auto-generated by Fern from our API Definition.

import typing

from .redacted_thinking_block import RedactedThinkingBlock
from .thinking_block import ThinkingBlock

ModelMessageEventThinkingBlocksItem = typing.Union[ThinkingBlock, RedactedThinkingBlock]
