# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_conversation_input_message import AgentConversationInputMessage
from .agent_skill_mount import AgentSkillMount


class NamedAgentRunInput(UniversalBaseModel):
    previous_response_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of a prior stored response. Pass to continue a stateful conversation.
    """

    variables: typing.Optional[typing.Dict[str, str]] = None
    skills: typing.Optional[typing.List[AgentSkillMount]] = None
    input: typing.Optional[typing.List[AgentConversationInputMessage]] = None
    agent_name: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
