# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class RequireApprovalToolsSelectorTag(enum.StrEnum):
    ALL = "@all"
    WRITE = "@write"
    DESTRUCTIVE = "@destructive"
    _UNKNOWN = "__REQUIREAPPROVALTOOLSSELECTORTAG_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "RequireApprovalToolsSelectorTag":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        all_: typing.Callable[[], T_Result],
        write: typing.Callable[[], T_Result],
        destructive: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is RequireApprovalToolsSelectorTag.ALL:
            return all_()
        if self is RequireApprovalToolsSelectorTag.WRITE:
            return write()
        if self is RequireApprovalToolsSelectorTag.DESTRUCTIVE:
            return destructive()
        return _unknown_member(self._value_)
