# This file was auto-generated by Fern from our API Definition.

import typing

from .require_approval_tools_selector_tag import RequireApprovalToolsSelectorTag

RequireApprovalToolSelectorItem = typing.Union[RequireApprovalToolsSelectorTag, str]
