# This file was auto-generated by Fern from our API Definition.

import typing

from .response_format_json_schema import ResponseFormatJsonSchema
from .response_format_one import ResponseFormatOne
from .response_format_zero import ResponseFormatZero

ResponseFormat = typing.Union[ResponseFormatZero, ResponseFormatOne, ResponseFormatJsonSchema]
