# This file was auto-generated by Fern from our API Definition.

import typing

from .draft_session import DraftSession
from .session import Session

SearchSessionsResponseDataItem = typing.Union[Session, DraftSession]
