# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_completion_usage import AgentCompletionUsage
from .agent_finish_reason import AgentFinishReason
from .agent_info import AgentInfo
from .agent_mcp_initialization_info import AgentMcpInitializationInfo
from .agent_mcp_server_auth_info import AgentMcpServerAuthInfo
from .agent_parent import AgentParent
from .agent_tool_call_ref import AgentToolCallRef
from .created_by_subject import CreatedBySubject
from .sequenced_turn_streaming_output_event_audio import SequencedTurnStreamingOutputEventAudio
from .sequenced_turn_streaming_output_event_context_item import SequencedTurnStreamingOutputEventContextItem
from .sequenced_turn_streaming_output_event_function_call import SequencedTurnStreamingOutputEventFunctionCall
from .sequenced_turn_streaming_output_event_thinking_blocks_item import (
    SequencedTurnStreamingOutputEventThinkingBlocksItem,
)
from .sequenced_turn_streaming_output_event_usage import SequencedTurnStreamingOutputEventUsage


class SequencedTurnStreamingOutputEvent(UniversalBaseModel):
    audio: typing.Optional[SequencedTurnStreamingOutputEventAudio] = None
    content: typing.Optional[typing.List[AgentMcpInitializationInfo]] = None
    function_call: typing.Optional[SequencedTurnStreamingOutputEventFunctionCall] = None
    name: typing.Optional[str] = None
    refusal: typing.Optional[str] = None
    thinking_blocks: typing.Optional[typing.List[SequencedTurnStreamingOutputEventThinkingBlocksItem]] = None
    tool_calls: typing.Optional[typing.List[AgentToolCallRef]] = None
    type: typing.Optional[typing.Literal["turn.created"]] = None
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the event
    """

    thread_id: typing.Optional[str] = None
    finish_reason: typing.Optional[AgentFinishReason] = None
    created_at: typing.Optional[str] = None
    usage: typing.Optional[SequencedTurnStreamingOutputEventUsage] = None
    reasoning_content: typing.Optional[str] = None
    tool_call_id: typing.Optional[str] = None
    agent_info: typing.Optional[AgentInfo] = None
    parent: typing.Optional[AgentParent] = None
    title: typing.Optional[str] = None
    reason: typing.Optional[typing.Literal["compaction"]] = None
    context: typing.Optional[typing.List[SequencedTurnStreamingOutputEventContextItem]] = None
    current_context_usage: typing.Optional[AgentCompletionUsage] = None
    compaction_llm_usage: typing.Optional[AgentCompletionUsage] = None
    servers: typing.Optional[typing.List[AgentMcpServerAuthInfo]] = None
    sandbox_id: typing.Optional[str] = None
    turn_id: typing.Optional[str] = None
    previous_turn_id: typing.Optional[str] = None
    created_by: typing.Optional[CreatedBySubject] = None
    sequence_number: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
