# This file was auto-generated by Fern from our API Definition.

import typing

from .sequenced_turn_persisted_event_content_one_item import SequencedTurnPersistedEventContentOneItem

SequencedTurnPersistedEventContent = typing.Union[str, typing.List[SequencedTurnPersistedEventContentOneItem]]
