# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SessionSubject(UniversalBaseModel):
    subject_id: str
    subject_type: str
    subject_slug: typing.Optional[str] = None
    subject_display_name: typing.Optional[str] = None
    subject_pat_name: typing.Optional[str] = None
    subject_controller_name: typing.Optional[str] = None
    subject_external_identity_slug: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
