# This file was auto-generated by Fern from our API Definition.

import typing

from .git_source_skill_mount import GitSourceSkillMount
from .registered_skill_mount import RegisteredSkillMount

SkillMount = typing.Union[GitSourceSkillMount, RegisteredSkillMount]
