# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SkillMountGit(UniversalBaseModel):
    type: typing.Literal["git"] = "git"
    url: str = pydantic.Field()
    """
    Full HTTPS URL of a GitHub or GitLab repository.
    """

    path: typing.Optional[str] = pydantic.Field(default=None)
    """
    Path to the skill directory within the repository. Omit to use the repository root.
    """

    name: str = pydantic.Field()
    """
    Name for the skill, used as directory name in sandbox.
    """

    ref: str = pydantic.Field()
    """
    Git ref — branch name, tag, or commit SHA.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
