# This file was auto-generated by Fern from our API Definition.

import typing

from .skill_mount_git import SkillMountGit
from .skill_mount_registry import SkillMountRegistry

SkillMount = typing.Union[SkillMountGit, SkillMountRegistry]
