# This file was auto-generated by Fern from our API Definition.

import typing

from .thread_state_done import ThreadStateDone
from .thread_state_error import ThreadStateError

ThreadState = typing.Union[ThreadStateDone, ThreadStateError]
