# This file was auto-generated by Fern from our API Definition.

import typing

from .thread_done_completed import ThreadDoneCompleted
from .thread_done_error import ThreadDoneError

ThreadDoneEvent = typing.Union[ThreadDoneCompleted, ThreadDoneError]
