# This file was auto-generated by Fern from our API Definition.

import typing

from .turn_output_event_content_one_item import TurnOutputEventContentOneItem

TurnOutputEventContent = typing.Union[str, typing.List[TurnOutputEventContentOneItem]]
