# This file was auto-generated by Fern from our API Definition.

import typing

from .user_message import UserMessage
from .user_tool_approval_event import UserToolApprovalEvent
from .user_tool_response_event import UserToolResponseEvent

TurnInputItem = typing.Union[UserMessage, UserToolApprovalEvent, UserToolResponseEvent]
