# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .approval_decision import ApprovalDecision
from .user_message_content import UserMessageContent


class TurnInputItem_UserMessage(UniversalBaseModel):
    type: typing.Literal["user.message"] = "user.message"
    content: UserMessageContent

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow


class TurnInputItem_UserToolApproval(UniversalBaseModel):
    type: typing.Literal["user.tool_approval"] = "user.tool_approval"
    thread_id: str
    tool_call_id: str
    approval: ApprovalDecision

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow


class TurnInputItem_UserToolResponse(UniversalBaseModel):
    type: typing.Literal["user.tool_response"] = "user.tool_response"
    thread_id: str
    tool_call_id: str
    content: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow


TurnInputItem = typing_extensions.Annotated[
    typing.Union[TurnInputItem_UserMessage, TurnInputItem_UserToolApproval, TurnInputItem_UserToolResponse],
    pydantic.Field(discriminator="type"),
]
