# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .subject import Subject
from .turn_state_running import TurnStateRunning


class TurnCreatedEvent(UniversalBaseModel):
    type: typing.Literal["turn.created"] = "turn.created"
    id: str = pydantic.Field()
    """
    Unique identifier for the event
    """

    turn_id: str
    previous_turn_id: typing.Optional[str] = None
    state: TurnStateRunning
    created_by: Subject
    created_at: str
    thread_id: typing.Optional[str] = None
    sequence_number: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
