# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .subject import Subject
from .turn_input_item import TurnInputItem
from .turn_state import TurnState


class Turn(UniversalBaseModel):
    id: str
    session_id: str
    previous_turn_id: typing.Optional[str] = None
    input: typing.Optional[typing.List[TurnInputItem]] = None
    state: TurnState
    created_by_subject: Subject
    created_at: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
