# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .finish_reason import FinishReason
from .model_message_usage import ModelMessageUsage
from .tool_call import ToolCall
from .turn_state_done_output_content import TurnStateDoneOutputContent


class TurnStateDoneOutput(UniversalBaseModel):
    content: typing.Optional[TurnStateDoneOutputContent] = None
    name: typing.Optional[str] = None
    refusal: typing.Optional[str] = None
    reasoning_content: typing.Optional[str] = None
    tool_calls: typing.Optional[typing.List[ToolCall]] = None
    type: typing.Literal["model.message"] = "model.message"
    id: str = pydantic.Field()
    """
    Unique identifier for the event
    """

    thread_id: str
    finish_reason: typing.Optional[FinishReason] = None
    created_at: str
    usage: typing.Optional[ModelMessageUsage] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
