# This file was auto-generated by Fern from our API Definition.

import typing

from .turn_streaming_event_content_one_item import TurnStreamingEventContentOneItem

TurnStreamingEventContent = typing.Union[str, typing.List[TurnStreamingEventContentOneItem]]
