# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .action_required_event import ActionRequiredEvent
from .turn_state_done_output import TurnStateDoneOutput


class TurnStateDone(UniversalBaseModel):
    status: typing.Literal["done"] = "done"
    output: typing.Optional[TurnStateDoneOutput] = None
    required_actions: typing.List[ActionRequiredEvent]
    completed_at: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
