# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .turn_state_done_output_usage_input_tokens_breakdown import TurnStateDoneOutputUsageInputTokensBreakdown


class TurnStateDoneOutputUsage(UniversalBaseModel):
    input_tokens: int
    output_tokens: int
    cache_read_tokens: typing.Optional[int] = None
    cache_write_tokens: typing.Optional[int] = None
    input_tokens_breakdown: TurnStateDoneOutputUsageInputTokensBreakdown

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
