# This file was auto-generated by Fern from our API Definition.

import typing

from .turn_event_content_one_item import TurnEventContentOneItem

TurnEventContent = typing.Union[str, typing.List[TurnEventContentOneItem]]
