# This file was auto-generated by Fern from our API Definition.

import typing

from .user_message import UserMessage
from .user_tool_approval_message import UserToolApprovalMessage
from .user_tool_response_message import UserToolResponseMessage

TurnInputItem = typing.Union[UserMessage, UserToolApprovalMessage, UserToolResponseMessage]
