# This file was auto-generated by Fern from our API Definition.

import typing

from .turn_state_cancelled import TurnStateCancelled
from .turn_state_done import TurnStateDone
from .turn_state_error import TurnStateError

TurnDoneEventState = typing.Union[TurnStateDone, TurnStateCancelled, TurnStateError]
