# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_finish_reason import AgentFinishReason
from .agent_info import AgentInfo
from .agent_mcp_initialization_info import AgentMcpInitializationInfo
from .agent_mcp_server_auth_info import AgentMcpServerAuthInfo
from .agent_parent import AgentParent
from .agent_tool_call_ref import AgentToolCallRef
from .model_message_event import ModelMessageEvent
from .turn_output_event_audio import TurnOutputEventAudio
from .turn_output_event_function_call import TurnOutputEventFunctionCall
from .turn_output_event_thinking_blocks_item import TurnOutputEventThinkingBlocksItem
from .turn_output_event_usage import TurnOutputEventUsage


class TurnOutputEvent(UniversalBaseModel):
    audio: typing.Optional[TurnOutputEventAudio] = None
    content: typing.Optional[typing.List[AgentMcpInitializationInfo]] = None
    function_call: typing.Optional[TurnOutputEventFunctionCall] = None
    name: typing.Optional[str] = None
    refusal: typing.Optional[str] = None
    thinking_blocks: typing.Optional[typing.List[TurnOutputEventThinkingBlocksItem]] = None
    tool_calls: typing.Optional[typing.List[AgentToolCallRef]] = None
    type: typing.Optional[typing.Literal["tool.response_required"]] = None
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the event
    """

    thread_id: typing.Optional[str] = None
    finish_reason: typing.Optional[AgentFinishReason] = None
    created_at: typing.Optional[str] = None
    usage: typing.Optional[TurnOutputEventUsage] = None
    tool_call_id: typing.Optional[str] = None
    agent_info: typing.Optional[AgentInfo] = None
    parent: typing.Optional[AgentParent] = None
    title: typing.Optional[str] = None
    output: typing.Optional[ModelMessageEvent] = None
    status: typing.Optional[typing.Literal["error"]] = None
    error: typing.Optional[str] = None
    servers: typing.Optional[typing.List[AgentMcpServerAuthInfo]] = None
    sandbox_id: typing.Optional[str] = None
    sequence_number: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
