# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_enriched_tool_call import AgentEnrichedToolCall
from .agent_finish_reason import AgentFinishReason
from .turn_state_done_output_audio import TurnStateDoneOutputAudio
from .turn_state_done_output_content import TurnStateDoneOutputContent
from .turn_state_done_output_function_call import TurnStateDoneOutputFunctionCall
from .turn_state_done_output_thinking_blocks_item import TurnStateDoneOutputThinkingBlocksItem
from .turn_state_done_output_usage import TurnStateDoneOutputUsage


class TurnStateDoneOutput(UniversalBaseModel):
    audio: typing.Optional[TurnStateDoneOutputAudio] = None
    content: typing.Optional[TurnStateDoneOutputContent] = None
    function_call: typing.Optional[TurnStateDoneOutputFunctionCall] = None
    name: typing.Optional[str] = None
    refusal: typing.Optional[str] = None
    thinking_blocks: typing.Optional[typing.List[TurnStateDoneOutputThinkingBlocksItem]] = None
    tool_calls: typing.Optional[typing.List[AgentEnrichedToolCall]] = None
    type: typing.Literal["model.message"] = "model.message"
    id: str = pydantic.Field()
    """
    Unique identifier for the event
    """

    thread_id: str
    finish_reason: typing.Optional[AgentFinishReason] = None
    created_at: str
    usage: typing.Optional[TurnStateDoneOutputUsage] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
