# This file was auto-generated by Fern from our API Definition.

import typing

from .turn_state_done_output_content_one_item import TurnStateDoneOutputContentOneItem

TurnStateDoneOutputContent = typing.Union[str, typing.List[TurnStateDoneOutputContentOneItem]]
