# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_approval_decision import AgentApprovalDecision


class UserToolApprovalMessage(UniversalBaseModel):
    type: typing.Literal["user.tool_approval"] = "user.tool_approval"
    thread_id: str
    tool_call_id: str
    approval: AgentApprovalDecision

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
