# This file was auto-generated by Fern from our API Definition.

import typing

from .file_content import FileContent
from .text_content import TextContent

UserMessageContentItem = typing.Union[TextContent, FileContent]
