# This file was auto-generated by Fern from our API Definition.

import typing

from .user_message_content_item import UserMessageContentItem

UserMessageContent = typing.Union[str, typing.List[UserMessageContentItem]]
