# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import os
import typing

import httpx
from .core.api_error import ApiError
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.logging import LogConfig, Logger
from .environment import TruefoundryGatewayEnvironment

if typing.TYPE_CHECKING:
    from .agents.client import AgentsClient, AsyncAgentsClient


class BaseTruefoundryGateway:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : TruefoundryGatewayEnvironment
        The environment to use for requests from the client. from .environment import TruefoundryGatewayEnvironment



        Defaults to TruefoundryGatewayEnvironment.DEFAULT



    scheme : typing.Optional[str]
        Server URL variable for 'scheme'. Defaults to 'https'.

    gateway_base_url : typing.Optional[str]
        Server URL variable for 'gatewayBaseURL'. Defaults to 'gateway.truefoundry.ai'.

    tenant_name : typing.Optional[str]
        Server URL variable for 'tenantName'. Defaults to 'truefoundry'.

    token : typing.Optional[typing.Union[str, typing.Callable[[], str]]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from truefoundry_gateway_sdk import TruefoundryGateway

    client = TruefoundryGateway(
        token="YOUR_TOKEN",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: TruefoundryGatewayEnvironment = TruefoundryGatewayEnvironment.DEFAULT,
        scheme: typing.Optional[str] = None,
        gateway_base_url: typing.Optional[str] = None,
        tenant_name: typing.Optional[str] = None,
        token: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = os.getenv("TFY_API_KEY"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        if token is None:
            raise ApiError(body="The client must be instantiated be either passing in token or setting TFY_API_KEY")
        if scheme is not None or gateway_base_url is not None or tenant_name is not None:
            _scheme = scheme if scheme is not None else "https"
            _gateway_base_url = gateway_base_url if gateway_base_url is not None else "gateway.truefoundry.ai"
            _tenant_name = tenant_name if tenant_name is not None else "truefoundry"
            base_url = "{scheme}://{gatewayBaseURL}/{tenantName}".format(
                scheme=_scheme, gatewayBaseURL=_gateway_base_url, tenantName=_tenant_name
            )
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            token=token,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            logging=logging,
        )
        self._agents: typing.Optional[AgentsClient] = None

    @property
    def agents(self):
        if self._agents is None:
            from .agents.client import AgentsClient  # noqa: E402

            self._agents = AgentsClient(client_wrapper=self._client_wrapper)
        return self._agents


def _make_default_async_client(
    timeout: typing.Optional[float],
    follow_redirects: typing.Optional[bool],
) -> httpx.AsyncClient:
    try:
        import httpx_aiohttp  # type: ignore[import-not-found]
    except ImportError:
        pass
    else:
        if follow_redirects is not None:
            return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout, follow_redirects=follow_redirects)
        return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout)

    if follow_redirects is not None:
        return httpx.AsyncClient(timeout=timeout, follow_redirects=follow_redirects)
    return httpx.AsyncClient(timeout=timeout)


class AsyncBaseTruefoundryGateway:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : TruefoundryGatewayEnvironment
        The environment to use for requests from the client. from .environment import TruefoundryGatewayEnvironment



        Defaults to TruefoundryGatewayEnvironment.DEFAULT



    scheme : typing.Optional[str]
        Server URL variable for 'scheme'. Defaults to 'https'.

    gateway_base_url : typing.Optional[str]
        Server URL variable for 'gatewayBaseURL'. Defaults to 'gateway.truefoundry.ai'.

    tenant_name : typing.Optional[str]
        Server URL variable for 'tenantName'. Defaults to 'truefoundry'.

    token : typing.Optional[typing.Union[str, typing.Callable[[], str]]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    async_token : typing.Optional[typing.Callable[[], typing.Awaitable[str]]]
        An async callable that returns a bearer token. Use this when token acquisition involves async I/O (e.g., refreshing tokens via an async HTTP client). When provided, this is used instead of the synchronous token for async requests.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from truefoundry_gateway_sdk import AsyncTruefoundryGateway

    client = AsyncTruefoundryGateway(
        token="YOUR_TOKEN",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: TruefoundryGatewayEnvironment = TruefoundryGatewayEnvironment.DEFAULT,
        scheme: typing.Optional[str] = None,
        gateway_base_url: typing.Optional[str] = None,
        tenant_name: typing.Optional[str] = None,
        token: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = os.getenv("TFY_API_KEY"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        async_token: typing.Optional[typing.Callable[[], typing.Awaitable[str]]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        if token is None:
            raise ApiError(body="The client must be instantiated be either passing in token or setting TFY_API_KEY")
        if scheme is not None or gateway_base_url is not None or tenant_name is not None:
            _scheme = scheme if scheme is not None else "https"
            _gateway_base_url = gateway_base_url if gateway_base_url is not None else "gateway.truefoundry.ai"
            _tenant_name = tenant_name if tenant_name is not None else "truefoundry"
            base_url = "{scheme}://{gatewayBaseURL}/{tenantName}".format(
                scheme=_scheme, gatewayBaseURL=_gateway_base_url, tenantName=_tenant_name
            )
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            token=token,
            headers=headers,
            async_token=async_token,
            httpx_client=httpx_client
            if httpx_client is not None
            else _make_default_async_client(timeout=_defaulted_timeout, follow_redirects=follow_redirects),
            timeout=_defaulted_timeout,
            logging=logging,
        )
        self._agents: typing.Optional[AsyncAgentsClient] = None

    @property
    def agents(self):
        if self._agents is None:
            from .agents.client import AsyncAgentsClient  # noqa: E402

            self._agents = AsyncAgentsClient(client_wrapper=self._client_wrapper)
        return self._agents


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: TruefoundryGatewayEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
