# This file was auto-generated by Fern from our API Definition.

import os
import typing

import httpx
from .base_client import AsyncBaseTrueFoundryGateway, BaseTrueFoundryGateway
from .core.logging import LogConfig, Logger
from .private.agents.client import AgentsClient, AsyncAgentsClient


class TrueFoundryGateway(BaseTrueFoundryGateway):
    """Synchronous client for the TrueFoundry Gateway API."""

    def __init__(
        self,
        *,
        base_url: str,
        api_key: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = os.getenv("TFY_API_KEY"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        stream_reconnection_enabled: typing.Optional[bool] = None,
        max_stream_reconnection_attempts: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        super().__init__(
            base_url=base_url,
            api_key=api_key,
            headers=headers,
            timeout=timeout,
            max_retries=max_retries,
            stream_reconnection_enabled=stream_reconnection_enabled,
            max_stream_reconnection_attempts=max_stream_reconnection_attempts,
            follow_redirects=follow_redirects,
            httpx_client=httpx_client,
            logging=logging,
        )
        self._agents: typing.Optional[AgentsClient] = None

    @property
    def agents(self) -> AgentsClient:
        """Agent sessions and turns."""
        if self._agents is None:
            self._agents = AgentsClient(client_wrapper=self._client_wrapper)
        return self._agents


class AsyncTrueFoundryGateway(AsyncBaseTrueFoundryGateway):
    """Asynchronous client for the TrueFoundry Gateway API."""

    def __init__(
        self,
        *,
        base_url: str,
        api_key: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = os.getenv("TFY_API_KEY"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        async_token: typing.Optional[typing.Callable[[], typing.Awaitable[str]]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        stream_reconnection_enabled: typing.Optional[bool] = None,
        max_stream_reconnection_attempts: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        super().__init__(
            base_url=base_url,
            api_key=api_key,
            headers=headers,
            async_token=async_token,
            timeout=timeout,
            max_retries=max_retries,
            stream_reconnection_enabled=stream_reconnection_enabled,
            max_stream_reconnection_attempts=max_stream_reconnection_attempts,
            follow_redirects=follow_redirects,
            httpx_client=httpx_client,
            logging=logging,
        )
        self._agents: typing.Optional[AsyncAgentsClient] = None

    @property
    def agents(self) -> AsyncAgentsClient:
        """Agent sessions and turns."""
        if self._agents is None:
            self._agents = AsyncAgentsClient(client_wrapper=self._client_wrapper)
        return self._agents
